<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class BcVehiculos extends \AppBundle\Entity\BcVehiculos implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\BcVehiculos' . "\0" . 'marcamodelo', '' . "\0" . 'AppBundle\\Entity\\BcVehiculos' . "\0" . 'anio', '' . "\0" . 'AppBundle\\Entity\\BcVehiculos' . "\0" . 'tarjetacirculacion', '' . "\0" . 'AppBundle\\Entity\\BcVehiculos' . "\0" . 'portal', '' . "\0" . 'AppBundle\\Entity\\BcVehiculos' . "\0" . 'vehiculosid', '' . "\0" . 'AppBundle\\Entity\\BcVehiculos' . "\0" . 'solicitudid', '' . "\0" . 'AppBundle\\Entity\\BcVehiculos' . "\0" . 'estatus'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\BcVehiculos' . "\0" . 'marcamodelo', '' . "\0" . 'AppBundle\\Entity\\BcVehiculos' . "\0" . 'anio', '' . "\0" . 'AppBundle\\Entity\\BcVehiculos' . "\0" . 'tarjetacirculacion', '' . "\0" . 'AppBundle\\Entity\\BcVehiculos' . "\0" . 'portal', '' . "\0" . 'AppBundle\\Entity\\BcVehiculos' . "\0" . 'vehiculosid', '' . "\0" . 'AppBundle\\Entity\\BcVehiculos' . "\0" . 'solicitudid', '' . "\0" . 'AppBundle\\Entity\\BcVehiculos' . "\0" . 'estatus'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (BcVehiculos $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setMarcamodelo($marcamodelo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMarcamodelo', [$marcamodelo]);

        return parent::setMarcamodelo($marcamodelo);
    }

    /**
     * {@inheritDoc}
     */
    public function getMarcamodelo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMarcamodelo', []);

        return parent::getMarcamodelo();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnio($anio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnio', [$anio]);

        return parent::setAnio($anio);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnio', []);

        return parent::getAnio();
    }

    /**
     * {@inheritDoc}
     */
    public function setTarjetacirculacion($tarjetacirculacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTarjetacirculacion', [$tarjetacirculacion]);

        return parent::setTarjetacirculacion($tarjetacirculacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getTarjetacirculacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTarjetacirculacion', []);

        return parent::getTarjetacirculacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setPortal($portal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPortal', [$portal]);

        return parent::setPortal($portal);
    }

    /**
     * {@inheritDoc}
     */
    public function getPortal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPortal', []);

        return parent::getPortal();
    }

    /**
     * {@inheritDoc}
     */
    public function getVehiculosid()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getVehiculosid();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVehiculosid', []);

        return parent::getVehiculosid();
    }

    /**
     * {@inheritDoc}
     */
    public function setSolicitudid(\AppBundle\Entity\BcSolicitudbeca $solicitudid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSolicitudid', [$solicitudid]);

        return parent::setSolicitudid($solicitudid);
    }

    /**
     * {@inheritDoc}
     */
    public function getSolicitudid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSolicitudid', []);

        return parent::getSolicitudid();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstatus(\AppBundle\Entity\BcEstatusvehiculos $estatus = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstatus', [$estatus]);

        return parent::setEstatus($estatus);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstatus', []);

        return parent::getEstatus();
    }

}
