<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class TpBoleto extends \AppBundle\Entity\TpBoleto implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\TpBoleto' . "\0" . 'fecha', '' . "\0" . 'AppBundle\\Entity\\TpBoleto' . "\0" . 'fechabitacora', '' . "\0" . 'AppBundle\\Entity\\TpBoleto' . "\0" . 'precio', '' . "\0" . 'AppBundle\\Entity\\TpBoleto' . "\0" . 'escaneado', '' . "\0" . 'AppBundle\\Entity\\TpBoleto' . "\0" . 'boletoid', '' . "\0" . 'AppBundle\\Entity\\TpBoleto' . "\0" . 'usuariocompraid', '' . "\0" . 'AppBundle\\Entity\\TpBoleto' . "\0" . 'alumnoid', '' . "\0" . 'AppBundle\\Entity\\TpBoleto' . "\0" . 'documentoporpagarid', '' . "\0" . 'AppBundle\\Entity\\TpBoleto' . "\0" . 'rutaid', '' . "\0" . 'AppBundle\\Entity\\TpBoleto' . "\0" . 'paradaid'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\TpBoleto' . "\0" . 'fecha', '' . "\0" . 'AppBundle\\Entity\\TpBoleto' . "\0" . 'fechabitacora', '' . "\0" . 'AppBundle\\Entity\\TpBoleto' . "\0" . 'precio', '' . "\0" . 'AppBundle\\Entity\\TpBoleto' . "\0" . 'escaneado', '' . "\0" . 'AppBundle\\Entity\\TpBoleto' . "\0" . 'boletoid', '' . "\0" . 'AppBundle\\Entity\\TpBoleto' . "\0" . 'usuariocompraid', '' . "\0" . 'AppBundle\\Entity\\TpBoleto' . "\0" . 'alumnoid', '' . "\0" . 'AppBundle\\Entity\\TpBoleto' . "\0" . 'documentoporpagarid', '' . "\0" . 'AppBundle\\Entity\\TpBoleto' . "\0" . 'rutaid', '' . "\0" . 'AppBundle\\Entity\\TpBoleto' . "\0" . 'paradaid'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (TpBoleto $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setFecha($fecha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFecha', [$fecha]);

        return parent::setFecha($fecha);
    }

    /**
     * {@inheritDoc}
     */
    public function getFecha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFecha', []);

        return parent::getFecha();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechabitacora($fechabitacora)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechabitacora', [$fechabitacora]);

        return parent::setFechabitacora($fechabitacora);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechabitacora()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechabitacora', []);

        return parent::getFechabitacora();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrecio($precio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrecio', [$precio]);

        return parent::setPrecio($precio);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrecio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrecio', []);

        return parent::getPrecio();
    }

    /**
     * {@inheritDoc}
     */
    public function setEscaneado($escaneado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEscaneado', [$escaneado]);

        return parent::setEscaneado($escaneado);
    }

    /**
     * {@inheritDoc}
     */
    public function getEscaneado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEscaneado', []);

        return parent::getEscaneado();
    }

    /**
     * {@inheritDoc}
     */
    public function getBoletoid()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getBoletoid();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBoletoid', []);

        return parent::getBoletoid();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuariocompraid(\AppBundle\Entity\Usuario $usuariocompraid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuariocompraid', [$usuariocompraid]);

        return parent::setUsuariocompraid($usuariocompraid);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuariocompraid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuariocompraid', []);

        return parent::getUsuariocompraid();
    }

    /**
     * {@inheritDoc}
     */
    public function setAlumnoid(\AppBundle\Entity\CeAlumno $alumnoid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAlumnoid', [$alumnoid]);

        return parent::setAlumnoid($alumnoid);
    }

    /**
     * {@inheritDoc}
     */
    public function getAlumnoid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAlumnoid', []);

        return parent::getAlumnoid();
    }

    /**
     * {@inheritDoc}
     */
    public function setDocumentoporpagarid(\AppBundle\Entity\CjDocumentoporpagar $documentoporpagarid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDocumentoporpagarid', [$documentoporpagarid]);

        return parent::setDocumentoporpagarid($documentoporpagarid);
    }

    /**
     * {@inheritDoc}
     */
    public function getDocumentoporpagarid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDocumentoporpagarid', []);

        return parent::getDocumentoporpagarid();
    }

    /**
     * {@inheritDoc}
     */
    public function setRutaid(\AppBundle\Entity\TpRuta $rutaid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRutaid', [$rutaid]);

        return parent::setRutaid($rutaid);
    }

    /**
     * {@inheritDoc}
     */
    public function getRutaid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRutaid', []);

        return parent::getRutaid();
    }

    /**
     * {@inheritDoc}
     */
    public function setParadaid(\AppBundle\Entity\TpRutaprecioparada $paradaid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParadaid', [$paradaid]);

        return parent::setParadaid($paradaid);
    }

    /**
     * {@inheritDoc}
     */
    public function getParadaid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParadaid', []);

        return parent::getParadaid();
    }

}
