<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class MaInforme extends \AppBundle\Entity\MaInforme implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\MaInforme' . "\0" . 'fecha', '' . "\0" . 'AppBundle\\Entity\\MaInforme' . "\0" . 'animo', '' . "\0" . 'AppBundle\\Entity\\MaInforme' . "\0" . 'panal', '' . "\0" . 'AppBundle\\Entity\\MaInforme' . "\0" . 'panal1', '' . "\0" . 'AppBundle\\Entity\\MaInforme' . "\0" . 'panal2', '' . "\0" . 'AppBundle\\Entity\\MaInforme' . "\0" . 'panaltipo', '' . "\0" . 'AppBundle\\Entity\\MaInforme' . "\0" . 'bano', '' . "\0" . 'AppBundle\\Entity\\MaInforme' . "\0" . 'bano1', '' . "\0" . 'AppBundle\\Entity\\MaInforme' . "\0" . 'bano2', '' . "\0" . 'AppBundle\\Entity\\MaInforme' . "\0" . 'banotipo', '' . "\0" . 'AppBundle\\Entity\\MaInforme' . "\0" . 'accidente', '' . "\0" . 'AppBundle\\Entity\\MaInforme' . "\0" . 'accidenteaviso', '' . "\0" . 'AppBundle\\Entity\\MaInforme' . "\0" . 'comida', '' . "\0" . 'AppBundle\\Entity\\MaInforme' . "\0" . 'comidaobservaciones', '' . "\0" . 'AppBundle\\Entity\\MaInforme' . "\0" . 'sueno', '' . "\0" . 'AppBundle\\Entity\\MaInforme' . "\0" . 'suenohoras', '' . "\0" . 'AppBundle\\Entity\\MaInforme' . "\0" . 'observaciones', '' . "\0" . 'AppBundle\\Entity\\MaInforme' . "\0" . 'estatus', '' . "\0" . 'AppBundle\\Entity\\MaInforme' . "\0" . 'visto', '' . "\0" . 'AppBundle\\Entity\\MaInforme' . "\0" . 'fechavisto', '' . "\0" . 'AppBundle\\Entity\\MaInforme' . "\0" . 'informeid', '' . "\0" . 'AppBundle\\Entity\\MaInforme' . "\0" . 'alumnoid'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\MaInforme' . "\0" . 'fecha', '' . "\0" . 'AppBundle\\Entity\\MaInforme' . "\0" . 'animo', '' . "\0" . 'AppBundle\\Entity\\MaInforme' . "\0" . 'panal', '' . "\0" . 'AppBundle\\Entity\\MaInforme' . "\0" . 'panal1', '' . "\0" . 'AppBundle\\Entity\\MaInforme' . "\0" . 'panal2', '' . "\0" . 'AppBundle\\Entity\\MaInforme' . "\0" . 'panaltipo', '' . "\0" . 'AppBundle\\Entity\\MaInforme' . "\0" . 'bano', '' . "\0" . 'AppBundle\\Entity\\MaInforme' . "\0" . 'bano1', '' . "\0" . 'AppBundle\\Entity\\MaInforme' . "\0" . 'bano2', '' . "\0" . 'AppBundle\\Entity\\MaInforme' . "\0" . 'banotipo', '' . "\0" . 'AppBundle\\Entity\\MaInforme' . "\0" . 'accidente', '' . "\0" . 'AppBundle\\Entity\\MaInforme' . "\0" . 'accidenteaviso', '' . "\0" . 'AppBundle\\Entity\\MaInforme' . "\0" . 'comida', '' . "\0" . 'AppBundle\\Entity\\MaInforme' . "\0" . 'comidaobservaciones', '' . "\0" . 'AppBundle\\Entity\\MaInforme' . "\0" . 'sueno', '' . "\0" . 'AppBundle\\Entity\\MaInforme' . "\0" . 'suenohoras', '' . "\0" . 'AppBundle\\Entity\\MaInforme' . "\0" . 'observaciones', '' . "\0" . 'AppBundle\\Entity\\MaInforme' . "\0" . 'estatus', '' . "\0" . 'AppBundle\\Entity\\MaInforme' . "\0" . 'visto', '' . "\0" . 'AppBundle\\Entity\\MaInforme' . "\0" . 'fechavisto', '' . "\0" . 'AppBundle\\Entity\\MaInforme' . "\0" . 'informeid', '' . "\0" . 'AppBundle\\Entity\\MaInforme' . "\0" . 'alumnoid'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (MaInforme $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setFecha($fecha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFecha', [$fecha]);

        return parent::setFecha($fecha);
    }

    /**
     * {@inheritDoc}
     */
    public function getFecha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFecha', []);

        return parent::getFecha();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnimo($animo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnimo', [$animo]);

        return parent::setAnimo($animo);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnimo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnimo', []);

        return parent::getAnimo();
    }

    /**
     * {@inheritDoc}
     */
    public function setPanal($panal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPanal', [$panal]);

        return parent::setPanal($panal);
    }

    /**
     * {@inheritDoc}
     */
    public function getPanal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPanal', []);

        return parent::getPanal();
    }

    /**
     * {@inheritDoc}
     */
    public function setPanal1($panal1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPanal1', [$panal1]);

        return parent::setPanal1($panal1);
    }

    /**
     * {@inheritDoc}
     */
    public function getPanal1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPanal1', []);

        return parent::getPanal1();
    }

    /**
     * {@inheritDoc}
     */
    public function setPanal2($panal2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPanal2', [$panal2]);

        return parent::setPanal2($panal2);
    }

    /**
     * {@inheritDoc}
     */
    public function getPanal2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPanal2', []);

        return parent::getPanal2();
    }

    /**
     * {@inheritDoc}
     */
    public function setPanaltipo($panaltipo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPanaltipo', [$panaltipo]);

        return parent::setPanaltipo($panaltipo);
    }

    /**
     * {@inheritDoc}
     */
    public function getPanaltipo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPanaltipo', []);

        return parent::getPanaltipo();
    }

    /**
     * {@inheritDoc}
     */
    public function setBano($bano)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBano', [$bano]);

        return parent::setBano($bano);
    }

    /**
     * {@inheritDoc}
     */
    public function getBano()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBano', []);

        return parent::getBano();
    }

    /**
     * {@inheritDoc}
     */
    public function setBano1($bano1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBano1', [$bano1]);

        return parent::setBano1($bano1);
    }

    /**
     * {@inheritDoc}
     */
    public function getBano1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBano1', []);

        return parent::getBano1();
    }

    /**
     * {@inheritDoc}
     */
    public function setBano2($bano2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBano2', [$bano2]);

        return parent::setBano2($bano2);
    }

    /**
     * {@inheritDoc}
     */
    public function getBano2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBano2', []);

        return parent::getBano2();
    }

    /**
     * {@inheritDoc}
     */
    public function setBanotipo($banotipo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBanotipo', [$banotipo]);

        return parent::setBanotipo($banotipo);
    }

    /**
     * {@inheritDoc}
     */
    public function getBanotipo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBanotipo', []);

        return parent::getBanotipo();
    }

    /**
     * {@inheritDoc}
     */
    public function setAccidente($accidente)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAccidente', [$accidente]);

        return parent::setAccidente($accidente);
    }

    /**
     * {@inheritDoc}
     */
    public function getAccidente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAccidente', []);

        return parent::getAccidente();
    }

    /**
     * {@inheritDoc}
     */
    public function setAccidenteaviso($accidenteaviso)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAccidenteaviso', [$accidenteaviso]);

        return parent::setAccidenteaviso($accidenteaviso);
    }

    /**
     * {@inheritDoc}
     */
    public function getAccidenteaviso()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAccidenteaviso', []);

        return parent::getAccidenteaviso();
    }

    /**
     * {@inheritDoc}
     */
    public function setComida($comida)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComida', [$comida]);

        return parent::setComida($comida);
    }

    /**
     * {@inheritDoc}
     */
    public function getComida()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComida', []);

        return parent::getComida();
    }

    /**
     * {@inheritDoc}
     */
    public function setComidaobservaciones($comidaobservaciones)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComidaobservaciones', [$comidaobservaciones]);

        return parent::setComidaobservaciones($comidaobservaciones);
    }

    /**
     * {@inheritDoc}
     */
    public function getComidaobservaciones()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComidaobservaciones', []);

        return parent::getComidaobservaciones();
    }

    /**
     * {@inheritDoc}
     */
    public function setSueno($sueno)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSueno', [$sueno]);

        return parent::setSueno($sueno);
    }

    /**
     * {@inheritDoc}
     */
    public function getSueno()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSueno', []);

        return parent::getSueno();
    }

    /**
     * {@inheritDoc}
     */
    public function setSuenohoras($suenohoras)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSuenohoras', [$suenohoras]);

        return parent::setSuenohoras($suenohoras);
    }

    /**
     * {@inheritDoc}
     */
    public function getSuenohoras()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSuenohoras', []);

        return parent::getSuenohoras();
    }

    /**
     * {@inheritDoc}
     */
    public function setObservaciones($observaciones)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObservaciones', [$observaciones]);

        return parent::setObservaciones($observaciones);
    }

    /**
     * {@inheritDoc}
     */
    public function getObservaciones()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservaciones', []);

        return parent::getObservaciones();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstatus($estatus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstatus', [$estatus]);

        return parent::setEstatus($estatus);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstatus', []);

        return parent::getEstatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setVisto($visto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVisto', [$visto]);

        return parent::setVisto($visto);
    }

    /**
     * {@inheritDoc}
     */
    public function getVisto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVisto', []);

        return parent::getVisto();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechavisto($fechavisto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechavisto', [$fechavisto]);

        return parent::setFechavisto($fechavisto);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechavisto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechavisto', []);

        return parent::getFechavisto();
    }

    /**
     * {@inheritDoc}
     */
    public function getInformeid()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getInformeid();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInformeid', []);

        return parent::getInformeid();
    }

    /**
     * {@inheritDoc}
     */
    public function setAlumnoid(\AppBundle\Entity\CeAlumno $alumnoid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAlumnoid', [$alumnoid]);

        return parent::setAlumnoid($alumnoid);
    }

    /**
     * {@inheritDoc}
     */
    public function getAlumnoid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAlumnoid', []);

        return parent::getAlumnoid();
    }

}
