<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Sesion extends \AppBundle\Entity\Sesion implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Sesion' . "\0" . 'token', '' . "\0" . 'AppBundle\\Entity\\Sesion' . "\0" . 'finaliza', '' . "\0" . 'AppBundle\\Entity\\Sesion' . "\0" . 'inicia', '' . "\0" . 'AppBundle\\Entity\\Sesion' . "\0" . 'direccionip', '' . "\0" . 'AppBundle\\Entity\\Sesion' . "\0" . 'pantalla', '' . "\0" . 'AppBundle\\Entity\\Sesion' . "\0" . 'sesionid', '' . "\0" . 'AppBundle\\Entity\\Sesion' . "\0" . 'usuarioid'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Sesion' . "\0" . 'token', '' . "\0" . 'AppBundle\\Entity\\Sesion' . "\0" . 'finaliza', '' . "\0" . 'AppBundle\\Entity\\Sesion' . "\0" . 'inicia', '' . "\0" . 'AppBundle\\Entity\\Sesion' . "\0" . 'direccionip', '' . "\0" . 'AppBundle\\Entity\\Sesion' . "\0" . 'pantalla', '' . "\0" . 'AppBundle\\Entity\\Sesion' . "\0" . 'sesionid', '' . "\0" . 'AppBundle\\Entity\\Sesion' . "\0" . 'usuarioid'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Sesion $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setToken($token)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setToken', [$token]);

        return parent::setToken($token);
    }

    /**
     * {@inheritDoc}
     */
    public function getToken()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getToken', []);

        return parent::getToken();
    }

    /**
     * {@inheritDoc}
     */
    public function setFinaliza($finaliza)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFinaliza', [$finaliza]);

        return parent::setFinaliza($finaliza);
    }

    /**
     * {@inheritDoc}
     */
    public function getFinaliza()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFinaliza', []);

        return parent::getFinaliza();
    }

    /**
     * {@inheritDoc}
     */
    public function setInicia($inicia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInicia', [$inicia]);

        return parent::setInicia($inicia);
    }

    /**
     * {@inheritDoc}
     */
    public function getInicia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInicia', []);

        return parent::getInicia();
    }

    /**
     * {@inheritDoc}
     */
    public function setDireccionip($direccionip)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDireccionip', [$direccionip]);

        return parent::setDireccionip($direccionip);
    }

    /**
     * {@inheritDoc}
     */
    public function getDireccionip()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDireccionip', []);

        return parent::getDireccionip();
    }

    /**
     * {@inheritDoc}
     */
    public function setPantalla($pantalla)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPantalla', [$pantalla]);

        return parent::setPantalla($pantalla);
    }

    /**
     * {@inheritDoc}
     */
    public function getPantalla()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPantalla', []);

        return parent::getPantalla();
    }

    /**
     * {@inheritDoc}
     */
    public function getSesionid()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getSesionid();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSesionid', []);

        return parent::getSesionid();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuarioid(\AppBundle\Entity\Usuario $usuarioid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuarioid', [$usuarioid]);

        return parent::setUsuarioid($usuarioid);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuarioid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuarioid', []);

        return parent::getUsuarioid();
    }

}
