<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CeTallercurricular extends \AppBundle\Entity\CeTallercurricular implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\CeTallercurricular' . "\0" . 'nombre', '' . "\0" . 'AppBundle\\Entity\\CeTallercurricular' . "\0" . 'cupo', '' . "\0" . 'AppBundle\\Entity\\CeTallercurricular' . "\0" . 'cupomaxmasculino', '' . "\0" . 'AppBundle\\Entity\\CeTallercurricular' . "\0" . 'cupomaxfemenino', '' . "\0" . 'AppBundle\\Entity\\CeTallercurricular' . "\0" . 'inscripcionweb', '' . "\0" . 'AppBundle\\Entity\\CeTallercurricular' . "\0" . 'descripcion', '' . "\0" . 'AppBundle\\Entity\\CeTallercurricular' . "\0" . 'orden', '' . "\0" . 'AppBundle\\Entity\\CeTallercurricular' . "\0" . 'tallercurricularid', '' . "\0" . 'AppBundle\\Entity\\CeTallercurricular' . "\0" . 'cotitularid', '' . "\0" . 'AppBundle\\Entity\\CeTallercurricular' . "\0" . 'suplenteid', '' . "\0" . 'AppBundle\\Entity\\CeTallercurricular' . "\0" . 'clasificadorparaescolaresid', '' . "\0" . 'AppBundle\\Entity\\CeTallercurricular' . "\0" . 'profesorid', '' . "\0" . 'AppBundle\\Entity\\CeTallercurricular' . "\0" . 'talleranteriorid', '' . "\0" . 'AppBundle\\Entity\\CeTallercurricular' . "\0" . 'cicloid'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\CeTallercurricular' . "\0" . 'nombre', '' . "\0" . 'AppBundle\\Entity\\CeTallercurricular' . "\0" . 'cupo', '' . "\0" . 'AppBundle\\Entity\\CeTallercurricular' . "\0" . 'cupomaxmasculino', '' . "\0" . 'AppBundle\\Entity\\CeTallercurricular' . "\0" . 'cupomaxfemenino', '' . "\0" . 'AppBundle\\Entity\\CeTallercurricular' . "\0" . 'inscripcionweb', '' . "\0" . 'AppBundle\\Entity\\CeTallercurricular' . "\0" . 'descripcion', '' . "\0" . 'AppBundle\\Entity\\CeTallercurricular' . "\0" . 'orden', '' . "\0" . 'AppBundle\\Entity\\CeTallercurricular' . "\0" . 'tallercurricularid', '' . "\0" . 'AppBundle\\Entity\\CeTallercurricular' . "\0" . 'cotitularid', '' . "\0" . 'AppBundle\\Entity\\CeTallercurricular' . "\0" . 'suplenteid', '' . "\0" . 'AppBundle\\Entity\\CeTallercurricular' . "\0" . 'clasificadorparaescolaresid', '' . "\0" . 'AppBundle\\Entity\\CeTallercurricular' . "\0" . 'profesorid', '' . "\0" . 'AppBundle\\Entity\\CeTallercurricular' . "\0" . 'talleranteriorid', '' . "\0" . 'AppBundle\\Entity\\CeTallercurricular' . "\0" . 'cicloid'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (CeTallercurricular $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', [$nombre]);

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', []);

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setCupo($cupo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCupo', [$cupo]);

        return parent::setCupo($cupo);
    }

    /**
     * {@inheritDoc}
     */
    public function getCupo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCupo', []);

        return parent::getCupo();
    }

    /**
     * {@inheritDoc}
     */
    public function setCupomaxmasculino($cupomaxmasculino)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCupomaxmasculino', [$cupomaxmasculino]);

        return parent::setCupomaxmasculino($cupomaxmasculino);
    }

    /**
     * {@inheritDoc}
     */
    public function getCupomaxmasculino()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCupomaxmasculino', []);

        return parent::getCupomaxmasculino();
    }

    /**
     * {@inheritDoc}
     */
    public function setCupomaxfemenino($cupomaxfemenino)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCupomaxfemenino', [$cupomaxfemenino]);

        return parent::setCupomaxfemenino($cupomaxfemenino);
    }

    /**
     * {@inheritDoc}
     */
    public function getCupomaxfemenino()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCupomaxfemenino', []);

        return parent::getCupomaxfemenino();
    }

    /**
     * {@inheritDoc}
     */
    public function setInscripcionweb($inscripcionweb)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInscripcionweb', [$inscripcionweb]);

        return parent::setInscripcionweb($inscripcionweb);
    }

    /**
     * {@inheritDoc}
     */
    public function getInscripcionweb()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInscripcionweb', []);

        return parent::getInscripcionweb();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcion($descripcion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcion', [$descripcion]);

        return parent::setDescripcion($descripcion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcion', []);

        return parent::getDescripcion();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrden($orden)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrden', [$orden]);

        return parent::setOrden($orden);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrden()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrden', []);

        return parent::getOrden();
    }

    /**
     * {@inheritDoc}
     */
    public function getTallercurricularid()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getTallercurricularid();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTallercurricularid', []);

        return parent::getTallercurricularid();
    }

    /**
     * {@inheritDoc}
     */
    public function setCotitularid(\AppBundle\Entity\CeProfesor $cotitularid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCotitularid', [$cotitularid]);

        return parent::setCotitularid($cotitularid);
    }

    /**
     * {@inheritDoc}
     */
    public function getCotitularid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCotitularid', []);

        return parent::getCotitularid();
    }

    /**
     * {@inheritDoc}
     */
    public function setSuplenteid(\AppBundle\Entity\CeProfesor $suplenteid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSuplenteid', [$suplenteid]);

        return parent::setSuplenteid($suplenteid);
    }

    /**
     * {@inheritDoc}
     */
    public function getSuplenteid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSuplenteid', []);

        return parent::getSuplenteid();
    }

    /**
     * {@inheritDoc}
     */
    public function setClasificadorparaescolaresid(\AppBundle\Entity\CeClasificadorparaescolares $clasificadorparaescolaresid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClasificadorparaescolaresid', [$clasificadorparaescolaresid]);

        return parent::setClasificadorparaescolaresid($clasificadorparaescolaresid);
    }

    /**
     * {@inheritDoc}
     */
    public function getClasificadorparaescolaresid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClasificadorparaescolaresid', []);

        return parent::getClasificadorparaescolaresid();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfesorid(\AppBundle\Entity\CeProfesor $profesorid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfesorid', [$profesorid]);

        return parent::setProfesorid($profesorid);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfesorid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfesorid', []);

        return parent::getProfesorid();
    }

    /**
     * {@inheritDoc}
     */
    public function setTalleranteriorid(\AppBundle\Entity\CeTallercurricular $talleranteriorid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTalleranteriorid', [$talleranteriorid]);

        return parent::setTalleranteriorid($talleranteriorid);
    }

    /**
     * {@inheritDoc}
     */
    public function getTalleranteriorid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTalleranteriorid', []);

        return parent::getTalleranteriorid();
    }

    /**
     * {@inheritDoc}
     */
    public function setCicloid(\AppBundle\Entity\Ciclo $cicloid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCicloid', [$cicloid]);

        return parent::setCicloid($cicloid);
    }

    /**
     * {@inheritDoc}
     */
    public function getCicloid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCicloid', []);

        return parent::getCicloid();
    }

}
