<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CeCalificacionperiodoporalumno extends \AppBundle\Entity\CeCalificacionperiodoporalumno implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\CeCalificacionperiodoporalumno' . "\0" . 'calificacionantesredondeo', '' . "\0" . 'AppBundle\\Entity\\CeCalificacionperiodoporalumno' . "\0" . 'calificacion', '' . "\0" . 'AppBundle\\Entity\\CeCalificacionperiodoporalumno' . "\0" . 'observacion', '' . "\0" . 'AppBundle\\Entity\\CeCalificacionperiodoporalumno' . "\0" . 'avance', '' . "\0" . 'AppBundle\\Entity\\CeCalificacionperiodoporalumno' . "\0" . 'calificacionperiodoporalumnoid', '' . "\0" . 'AppBundle\\Entity\\CeCalificacionperiodoporalumno' . "\0" . 'materiapadrecalificacionperiodoporalumnoid', '' . "\0" . 'AppBundle\\Entity\\CeCalificacionperiodoporalumno' . "\0" . 'calificacionfinalporperiodoalumno', '' . "\0" . 'AppBundle\\Entity\\CeCalificacionperiodoporalumno' . "\0" . 'materiaporplanestudioid', '' . "\0" . 'AppBundle\\Entity\\CeCalificacionperiodoporalumno' . "\0" . 'materiaid', '' . "\0" . 'AppBundle\\Entity\\CeCalificacionperiodoporalumno' . "\0" . 'alumnoporcicloid', '' . "\0" . 'AppBundle\\Entity\\CeCalificacionperiodoporalumno' . "\0" . 'profesorpormateriaplanestudioid', '' . "\0" . 'AppBundle\\Entity\\CeCalificacionperiodoporalumno' . "\0" . 'alumnoid', '' . "\0" . 'AppBundle\\Entity\\CeCalificacionperiodoporalumno' . "\0" . 'periodoevaluacionid', '' . "\0" . 'AppBundle\\Entity\\CeCalificacionperiodoporalumno' . "\0" . 'ponderacionopcionid'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\CeCalificacionperiodoporalumno' . "\0" . 'calificacionantesredondeo', '' . "\0" . 'AppBundle\\Entity\\CeCalificacionperiodoporalumno' . "\0" . 'calificacion', '' . "\0" . 'AppBundle\\Entity\\CeCalificacionperiodoporalumno' . "\0" . 'observacion', '' . "\0" . 'AppBundle\\Entity\\CeCalificacionperiodoporalumno' . "\0" . 'avance', '' . "\0" . 'AppBundle\\Entity\\CeCalificacionperiodoporalumno' . "\0" . 'calificacionperiodoporalumnoid', '' . "\0" . 'AppBundle\\Entity\\CeCalificacionperiodoporalumno' . "\0" . 'materiapadrecalificacionperiodoporalumnoid', '' . "\0" . 'AppBundle\\Entity\\CeCalificacionperiodoporalumno' . "\0" . 'calificacionfinalporperiodoalumno', '' . "\0" . 'AppBundle\\Entity\\CeCalificacionperiodoporalumno' . "\0" . 'materiaporplanestudioid', '' . "\0" . 'AppBundle\\Entity\\CeCalificacionperiodoporalumno' . "\0" . 'materiaid', '' . "\0" . 'AppBundle\\Entity\\CeCalificacionperiodoporalumno' . "\0" . 'alumnoporcicloid', '' . "\0" . 'AppBundle\\Entity\\CeCalificacionperiodoporalumno' . "\0" . 'profesorpormateriaplanestudioid', '' . "\0" . 'AppBundle\\Entity\\CeCalificacionperiodoporalumno' . "\0" . 'alumnoid', '' . "\0" . 'AppBundle\\Entity\\CeCalificacionperiodoporalumno' . "\0" . 'periodoevaluacionid', '' . "\0" . 'AppBundle\\Entity\\CeCalificacionperiodoporalumno' . "\0" . 'ponderacionopcionid'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (CeCalificacionperiodoporalumno $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setCalificacionantesredondeo($calificacionantesredondeo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCalificacionantesredondeo', [$calificacionantesredondeo]);

        return parent::setCalificacionantesredondeo($calificacionantesredondeo);
    }

    /**
     * {@inheritDoc}
     */
    public function getCalificacionantesredondeo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCalificacionantesredondeo', []);

        return parent::getCalificacionantesredondeo();
    }

    /**
     * {@inheritDoc}
     */
    public function setCalificacion($calificacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCalificacion', [$calificacion]);

        return parent::setCalificacion($calificacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getCalificacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCalificacion', []);

        return parent::getCalificacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setObservacion($observacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObservacion', [$observacion]);

        return parent::setObservacion($observacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getObservacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservacion', []);

        return parent::getObservacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setAvance($avance)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAvance', [$avance]);

        return parent::setAvance($avance);
    }

    /**
     * {@inheritDoc}
     */
    public function getAvance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAvance', []);

        return parent::getAvance();
    }

    /**
     * {@inheritDoc}
     */
    public function getCalificacionperiodoporalumnoid()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getCalificacionperiodoporalumnoid();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCalificacionperiodoporalumnoid', []);

        return parent::getCalificacionperiodoporalumnoid();
    }

    /**
     * {@inheritDoc}
     */
    public function setMateriapadrecalificacionperiodoporalumnoid(\AppBundle\Entity\CeCalificacionperiodoporalumno $materiapadrecalificacionperiodoporalumnoid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMateriapadrecalificacionperiodoporalumnoid', [$materiapadrecalificacionperiodoporalumnoid]);

        return parent::setMateriapadrecalificacionperiodoporalumnoid($materiapadrecalificacionperiodoporalumnoid);
    }

    /**
     * {@inheritDoc}
     */
    public function getMateriapadrecalificacionperiodoporalumnoid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMateriapadrecalificacionperiodoporalumnoid', []);

        return parent::getMateriapadrecalificacionperiodoporalumnoid();
    }

    /**
     * {@inheritDoc}
     */
    public function setCalificacionfinalporperiodoalumno(\AppBundle\Entity\CeCalificacionfinalperiodoporalumno $calificacionfinalporperiodoalumno = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCalificacionfinalporperiodoalumno', [$calificacionfinalporperiodoalumno]);

        return parent::setCalificacionfinalporperiodoalumno($calificacionfinalporperiodoalumno);
    }

    /**
     * {@inheritDoc}
     */
    public function getCalificacionfinalporperiodoalumno()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCalificacionfinalporperiodoalumno', []);

        return parent::getCalificacionfinalporperiodoalumno();
    }

    /**
     * {@inheritDoc}
     */
    public function setMateriaporplanestudioid(\AppBundle\Entity\CeMateriaporplanestudios $materiaporplanestudioid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMateriaporplanestudioid', [$materiaporplanestudioid]);

        return parent::setMateriaporplanestudioid($materiaporplanestudioid);
    }

    /**
     * {@inheritDoc}
     */
    public function getMateriaporplanestudioid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMateriaporplanestudioid', []);

        return parent::getMateriaporplanestudioid();
    }

    /**
     * {@inheritDoc}
     */
    public function setMateriaid(\AppBundle\Entity\Materia $materiaid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMateriaid', [$materiaid]);

        return parent::setMateriaid($materiaid);
    }

    /**
     * {@inheritDoc}
     */
    public function getMateriaid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMateriaid', []);

        return parent::getMateriaid();
    }

    /**
     * {@inheritDoc}
     */
    public function setAlumnoporcicloid(\AppBundle\Entity\CeAlumnoporciclo $alumnoporcicloid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAlumnoporcicloid', [$alumnoporcicloid]);

        return parent::setAlumnoporcicloid($alumnoporcicloid);
    }

    /**
     * {@inheritDoc}
     */
    public function getAlumnoporcicloid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAlumnoporcicloid', []);

        return parent::getAlumnoporcicloid();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfesorpormateriaplanestudioid(\AppBundle\Entity\CeProfesorpormateriaplanestudios $profesorpormateriaplanestudioid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfesorpormateriaplanestudioid', [$profesorpormateriaplanestudioid]);

        return parent::setProfesorpormateriaplanestudioid($profesorpormateriaplanestudioid);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfesorpormateriaplanestudioid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfesorpormateriaplanestudioid', []);

        return parent::getProfesorpormateriaplanestudioid();
    }

    /**
     * {@inheritDoc}
     */
    public function setAlumnoid(\AppBundle\Entity\CeAlumno $alumnoid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAlumnoid', [$alumnoid]);

        return parent::setAlumnoid($alumnoid);
    }

    /**
     * {@inheritDoc}
     */
    public function getAlumnoid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAlumnoid', []);

        return parent::getAlumnoid();
    }

    /**
     * {@inheritDoc}
     */
    public function setPeriodoevaluacionid(\AppBundle\Entity\CePeriodoevaluacion $periodoevaluacionid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPeriodoevaluacionid', [$periodoevaluacionid]);

        return parent::setPeriodoevaluacionid($periodoevaluacionid);
    }

    /**
     * {@inheritDoc}
     */
    public function getPeriodoevaluacionid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPeriodoevaluacionid', []);

        return parent::getPeriodoevaluacionid();
    }

    /**
     * {@inheritDoc}
     */
    public function setPonderacionopcionid(\AppBundle\Entity\CePonderacionopcion $ponderacionopcionid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPonderacionopcionid', [$ponderacionopcionid]);

        return parent::setPonderacionopcionid($ponderacionopcionid);
    }

    /**
     * {@inheritDoc}
     */
    public function getPonderacionopcionid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPonderacionopcionid', []);

        return parent::getPonderacionopcionid();
    }

}
