<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CjPagodetalle extends \AppBundle\Entity\CjPagodetalle implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\CjPagodetalle' . "\0" . 'importe', '' . "\0" . 'AppBundle\\Entity\\CjPagodetalle' . "\0" . 'iva', '' . "\0" . 'AppBundle\\Entity\\CjPagodetalle' . "\0" . 'leyenda', '' . "\0" . 'AppBundle\\Entity\\CjPagodetalle' . "\0" . 'pagodetalleid', '' . "\0" . 'AppBundle\\Entity\\CjPagodetalle' . "\0" . 'documentoporpagarid', '' . "\0" . 'AppBundle\\Entity\\CjPagodetalle' . "\0" . 'pagoid', '' . "\0" . 'AppBundle\\Entity\\CjPagodetalle' . "\0" . 'pagoformapagoid', '' . "\0" . 'AppBundle\\Entity\\CjPagodetalle' . "\0" . 'subconceptoid'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\CjPagodetalle' . "\0" . 'importe', '' . "\0" . 'AppBundle\\Entity\\CjPagodetalle' . "\0" . 'iva', '' . "\0" . 'AppBundle\\Entity\\CjPagodetalle' . "\0" . 'leyenda', '' . "\0" . 'AppBundle\\Entity\\CjPagodetalle' . "\0" . 'pagodetalleid', '' . "\0" . 'AppBundle\\Entity\\CjPagodetalle' . "\0" . 'documentoporpagarid', '' . "\0" . 'AppBundle\\Entity\\CjPagodetalle' . "\0" . 'pagoid', '' . "\0" . 'AppBundle\\Entity\\CjPagodetalle' . "\0" . 'pagoformapagoid', '' . "\0" . 'AppBundle\\Entity\\CjPagodetalle' . "\0" . 'subconceptoid'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (CjPagodetalle $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setImporte($importe)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImporte', [$importe]);

        return parent::setImporte($importe);
    }

    /**
     * {@inheritDoc}
     */
    public function getImporte()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImporte', []);

        return parent::getImporte();
    }

    /**
     * {@inheritDoc}
     */
    public function setIva($iva)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIva', [$iva]);

        return parent::setIva($iva);
    }

    /**
     * {@inheritDoc}
     */
    public function getIva()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIva', []);

        return parent::getIva();
    }

    /**
     * {@inheritDoc}
     */
    public function setLeyenda($leyenda)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLeyenda', [$leyenda]);

        return parent::setLeyenda($leyenda);
    }

    /**
     * {@inheritDoc}
     */
    public function getLeyenda()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLeyenda', []);

        return parent::getLeyenda();
    }

    /**
     * {@inheritDoc}
     */
    public function getPagodetalleid()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getPagodetalleid();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPagodetalleid', []);

        return parent::getPagodetalleid();
    }

    /**
     * {@inheritDoc}
     */
    public function setDocumentoporpagarid(\AppBundle\Entity\CjDocumentoporpagar $documentoporpagarid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDocumentoporpagarid', [$documentoporpagarid]);

        return parent::setDocumentoporpagarid($documentoporpagarid);
    }

    /**
     * {@inheritDoc}
     */
    public function getDocumentoporpagarid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDocumentoporpagarid', []);

        return parent::getDocumentoporpagarid();
    }

    /**
     * {@inheritDoc}
     */
    public function setPagoid(\AppBundle\Entity\CjPago $pagoid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPagoid', [$pagoid]);

        return parent::setPagoid($pagoid);
    }

    /**
     * {@inheritDoc}
     */
    public function getPagoid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPagoid', []);

        return parent::getPagoid();
    }

    /**
     * {@inheritDoc}
     */
    public function setPagoformapagoid(\AppBundle\Entity\CjPagoformapago $pagoformapagoid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPagoformapagoid', [$pagoformapagoid]);

        return parent::setPagoformapagoid($pagoformapagoid);
    }

    /**
     * {@inheritDoc}
     */
    public function getPagoformapagoid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPagoformapagoid', []);

        return parent::getPagoformapagoid();
    }

    /**
     * {@inheritDoc}
     */
    public function setSubconceptoid(\AppBundle\Entity\CjSubconcepto $subconceptoid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSubconceptoid', [$subconceptoid]);

        return parent::setSubconceptoid($subconceptoid);
    }

    /**
     * {@inheritDoc}
     */
    public function getSubconceptoid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubconceptoid', []);

        return parent::getSubconceptoid();
    }

}
