<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Respuesta extends \AppBundle\Entity\Respuesta implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Respuesta' . "\0" . 'respuesta', '' . "\0" . 'AppBundle\\Entity\\Respuesta' . "\0" . 'correcta', '' . "\0" . 'AppBundle\\Entity\\Respuesta' . "\0" . 'valorporcentaje', '' . "\0" . 'AppBundle\\Entity\\Respuesta' . "\0" . 'respuestaid', '' . "\0" . 'AppBundle\\Entity\\Respuesta' . "\0" . 'complementoid', '' . "\0" . 'AppBundle\\Entity\\Respuesta' . "\0" . 'preguntaid'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Respuesta' . "\0" . 'respuesta', '' . "\0" . 'AppBundle\\Entity\\Respuesta' . "\0" . 'correcta', '' . "\0" . 'AppBundle\\Entity\\Respuesta' . "\0" . 'valorporcentaje', '' . "\0" . 'AppBundle\\Entity\\Respuesta' . "\0" . 'respuestaid', '' . "\0" . 'AppBundle\\Entity\\Respuesta' . "\0" . 'complementoid', '' . "\0" . 'AppBundle\\Entity\\Respuesta' . "\0" . 'preguntaid'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Respuesta $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setRespuesta($respuesta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRespuesta', [$respuesta]);

        return parent::setRespuesta($respuesta);
    }

    /**
     * {@inheritDoc}
     */
    public function getRespuesta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRespuesta', []);

        return parent::getRespuesta();
    }

    /**
     * {@inheritDoc}
     */
    public function setCorrecta($correcta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCorrecta', [$correcta]);

        return parent::setCorrecta($correcta);
    }

    /**
     * {@inheritDoc}
     */
    public function getCorrecta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCorrecta', []);

        return parent::getCorrecta();
    }

    /**
     * {@inheritDoc}
     */
    public function setValorporcentaje($valorporcentaje)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValorporcentaje', [$valorporcentaje]);

        return parent::setValorporcentaje($valorporcentaje);
    }

    /**
     * {@inheritDoc}
     */
    public function getValorporcentaje()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValorporcentaje', []);

        return parent::getValorporcentaje();
    }

    /**
     * {@inheritDoc}
     */
    public function getRespuestaid()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getRespuestaid();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRespuestaid', []);

        return parent::getRespuestaid();
    }

    /**
     * {@inheritDoc}
     */
    public function setComplementoid(\AppBundle\Entity\Complemento $complementoid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComplementoid', [$complementoid]);

        return parent::setComplementoid($complementoid);
    }

    /**
     * {@inheritDoc}
     */
    public function getComplementoid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComplementoid', []);

        return parent::getComplementoid();
    }

    /**
     * {@inheritDoc}
     */
    public function setPreguntaid(\AppBundle\Entity\Pregunta $preguntaid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPreguntaid', [$preguntaid]);

        return parent::setPreguntaid($preguntaid);
    }

    /**
     * {@inheritDoc}
     */
    public function getPreguntaid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPreguntaid', []);

        return parent::getPreguntaid();
    }

}
