<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CePeriodoevaluacion extends \AppBundle\Entity\CePeriodoevaluacion implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\CePeriodoevaluacion' . "\0" . 'descripcion', '' . "\0" . 'AppBundle\\Entity\\CePeriodoevaluacion' . "\0" . 'descripcioncorta', '' . "\0" . 'AppBundle\\Entity\\CePeriodoevaluacion' . "\0" . 'fechainicio', '' . "\0" . 'AppBundle\\Entity\\CePeriodoevaluacion' . "\0" . 'fechafin', '' . "\0" . 'AppBundle\\Entity\\CePeriodoevaluacion' . "\0" . 'porcentajecalificacionfinal', '' . "\0" . 'AppBundle\\Entity\\CePeriodoevaluacion' . "\0" . 'fechalimedicionplantilla', '' . "\0" . 'AppBundle\\Entity\\CePeriodoevaluacion' . "\0" . 'fechalimedicionprofesor', '' . "\0" . 'AppBundle\\Entity\\CePeriodoevaluacion' . "\0" . 'fechacapturacalinicio', '' . "\0" . 'AppBundle\\Entity\\CePeriodoevaluacion' . "\0" . 'fechacapturacalfin', '' . "\0" . 'AppBundle\\Entity\\CePeriodoevaluacion' . "\0" . 'fechapublicacionprevia', '' . "\0" . 'AppBundle\\Entity\\CePeriodoevaluacion' . "\0" . 'fechaperiodorevisioninicio', '' . "\0" . 'AppBundle\\Entity\\CePeriodoevaluacion' . "\0" . 'fechaperiodorevisionfin', '' . "\0" . 'AppBundle\\Entity\\CePeriodoevaluacion' . "\0" . 'fechapublicaciondefinitiva', '' . "\0" . 'AppBundle\\Entity\\CePeriodoevaluacion' . "\0" . 'periodoevaluacionid', '' . "\0" . 'AppBundle\\Entity\\CePeriodoevaluacion' . "\0" . 'conjuntoperiodoevaluacionid'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\CePeriodoevaluacion' . "\0" . 'descripcion', '' . "\0" . 'AppBundle\\Entity\\CePeriodoevaluacion' . "\0" . 'descripcioncorta', '' . "\0" . 'AppBundle\\Entity\\CePeriodoevaluacion' . "\0" . 'fechainicio', '' . "\0" . 'AppBundle\\Entity\\CePeriodoevaluacion' . "\0" . 'fechafin', '' . "\0" . 'AppBundle\\Entity\\CePeriodoevaluacion' . "\0" . 'porcentajecalificacionfinal', '' . "\0" . 'AppBundle\\Entity\\CePeriodoevaluacion' . "\0" . 'fechalimedicionplantilla', '' . "\0" . 'AppBundle\\Entity\\CePeriodoevaluacion' . "\0" . 'fechalimedicionprofesor', '' . "\0" . 'AppBundle\\Entity\\CePeriodoevaluacion' . "\0" . 'fechacapturacalinicio', '' . "\0" . 'AppBundle\\Entity\\CePeriodoevaluacion' . "\0" . 'fechacapturacalfin', '' . "\0" . 'AppBundle\\Entity\\CePeriodoevaluacion' . "\0" . 'fechapublicacionprevia', '' . "\0" . 'AppBundle\\Entity\\CePeriodoevaluacion' . "\0" . 'fechaperiodorevisioninicio', '' . "\0" . 'AppBundle\\Entity\\CePeriodoevaluacion' . "\0" . 'fechaperiodorevisionfin', '' . "\0" . 'AppBundle\\Entity\\CePeriodoevaluacion' . "\0" . 'fechapublicaciondefinitiva', '' . "\0" . 'AppBundle\\Entity\\CePeriodoevaluacion' . "\0" . 'periodoevaluacionid', '' . "\0" . 'AppBundle\\Entity\\CePeriodoevaluacion' . "\0" . 'conjuntoperiodoevaluacionid'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (CePeriodoevaluacion $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setDescripcion($descripcion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcion', [$descripcion]);

        return parent::setDescripcion($descripcion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcion', []);

        return parent::getDescripcion();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcioncorta($descripcioncorta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcioncorta', [$descripcioncorta]);

        return parent::setDescripcioncorta($descripcioncorta);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcioncorta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcioncorta', []);

        return parent::getDescripcioncorta();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechainicio($fechainicio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechainicio', [$fechainicio]);

        return parent::setFechainicio($fechainicio);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechainicio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechainicio', []);

        return parent::getFechainicio();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechafin($fechafin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechafin', [$fechafin]);

        return parent::setFechafin($fechafin);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechafin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechafin', []);

        return parent::getFechafin();
    }

    /**
     * {@inheritDoc}
     */
    public function setPorcentajecalificacionfinal($porcentajecalificacionfinal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPorcentajecalificacionfinal', [$porcentajecalificacionfinal]);

        return parent::setPorcentajecalificacionfinal($porcentajecalificacionfinal);
    }

    /**
     * {@inheritDoc}
     */
    public function getPorcentajecalificacionfinal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPorcentajecalificacionfinal', []);

        return parent::getPorcentajecalificacionfinal();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechalimedicionplantilla($fechalimedicionplantilla)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechalimedicionplantilla', [$fechalimedicionplantilla]);

        return parent::setFechalimedicionplantilla($fechalimedicionplantilla);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechalimedicionplantilla()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechalimedicionplantilla', []);

        return parent::getFechalimedicionplantilla();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechalimedicionprofesor($fechalimedicionprofesor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechalimedicionprofesor', [$fechalimedicionprofesor]);

        return parent::setFechalimedicionprofesor($fechalimedicionprofesor);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechalimedicionprofesor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechalimedicionprofesor', []);

        return parent::getFechalimedicionprofesor();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechacapturacalinicio($fechacapturacalinicio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechacapturacalinicio', [$fechacapturacalinicio]);

        return parent::setFechacapturacalinicio($fechacapturacalinicio);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechacapturacalinicio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechacapturacalinicio', []);

        return parent::getFechacapturacalinicio();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechacapturacalfin($fechacapturacalfin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechacapturacalfin', [$fechacapturacalfin]);

        return parent::setFechacapturacalfin($fechacapturacalfin);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechacapturacalfin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechacapturacalfin', []);

        return parent::getFechacapturacalfin();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechapublicacionprevia($fechapublicacionprevia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechapublicacionprevia', [$fechapublicacionprevia]);

        return parent::setFechapublicacionprevia($fechapublicacionprevia);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechapublicacionprevia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechapublicacionprevia', []);

        return parent::getFechapublicacionprevia();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaperiodorevisioninicio($fechaperiodorevisioninicio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaperiodorevisioninicio', [$fechaperiodorevisioninicio]);

        return parent::setFechaperiodorevisioninicio($fechaperiodorevisioninicio);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaperiodorevisioninicio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaperiodorevisioninicio', []);

        return parent::getFechaperiodorevisioninicio();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaperiodorevisionfin($fechaperiodorevisionfin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaperiodorevisionfin', [$fechaperiodorevisionfin]);

        return parent::setFechaperiodorevisionfin($fechaperiodorevisionfin);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaperiodorevisionfin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaperiodorevisionfin', []);

        return parent::getFechaperiodorevisionfin();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechapublicaciondefinitiva($fechapublicaciondefinitiva)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechapublicaciondefinitiva', [$fechapublicaciondefinitiva]);

        return parent::setFechapublicaciondefinitiva($fechapublicaciondefinitiva);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechapublicaciondefinitiva()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechapublicaciondefinitiva', []);

        return parent::getFechapublicaciondefinitiva();
    }

    /**
     * {@inheritDoc}
     */
    public function getPeriodoevaluacionid()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getPeriodoevaluacionid();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPeriodoevaluacionid', []);

        return parent::getPeriodoevaluacionid();
    }

    /**
     * {@inheritDoc}
     */
    public function setConjuntoperiodoevaluacionid(\AppBundle\Entity\CeConjuntoperiodoevaluacion $conjuntoperiodoevaluacionid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConjuntoperiodoevaluacionid', [$conjuntoperiodoevaluacionid]);

        return parent::setConjuntoperiodoevaluacionid($conjuntoperiodoevaluacionid);
    }

    /**
     * {@inheritDoc}
     */
    public function getConjuntoperiodoevaluacionid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConjuntoperiodoevaluacionid', []);

        return parent::getConjuntoperiodoevaluacionid();
    }

}
