<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CeAcuerdoextraordinario extends \AppBundle\Entity\CeAcuerdoextraordinario implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\CeAcuerdoextraordinario' . "\0" . 'intento', '' . "\0" . 'AppBundle\\Entity\\CeAcuerdoextraordinario' . "\0" . 'calificacion', '' . "\0" . 'AppBundle\\Entity\\CeAcuerdoextraordinario' . "\0" . 'calificacionfinal', '' . "\0" . 'AppBundle\\Entity\\CeAcuerdoextraordinario' . "\0" . 'acuerdoextraordinarioid', '' . "\0" . 'AppBundle\\Entity\\CeAcuerdoextraordinario' . "\0" . 'agendaextraordinarioid', '' . "\0" . 'AppBundle\\Entity\\CeAcuerdoextraordinario' . "\0" . 'documentoporpagarid', '' . "\0" . 'AppBundle\\Entity\\CeAcuerdoextraordinario' . "\0" . 'usuarioid', '' . "\0" . 'AppBundle\\Entity\\CeAcuerdoextraordinario' . "\0" . 'estatusextraordinarioid', '' . "\0" . 'AppBundle\\Entity\\CeAcuerdoextraordinario' . "\0" . 'extraordinarioid', '' . "\0" . 'AppBundle\\Entity\\CeAcuerdoextraordinario' . "\0" . 'periodoregularizacionid', '' . "\0" . 'AppBundle\\Entity\\CeAcuerdoextraordinario' . "\0" . 'tipoextraordinarioid'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\CeAcuerdoextraordinario' . "\0" . 'intento', '' . "\0" . 'AppBundle\\Entity\\CeAcuerdoextraordinario' . "\0" . 'calificacion', '' . "\0" . 'AppBundle\\Entity\\CeAcuerdoextraordinario' . "\0" . 'calificacionfinal', '' . "\0" . 'AppBundle\\Entity\\CeAcuerdoextraordinario' . "\0" . 'acuerdoextraordinarioid', '' . "\0" . 'AppBundle\\Entity\\CeAcuerdoextraordinario' . "\0" . 'agendaextraordinarioid', '' . "\0" . 'AppBundle\\Entity\\CeAcuerdoextraordinario' . "\0" . 'documentoporpagarid', '' . "\0" . 'AppBundle\\Entity\\CeAcuerdoextraordinario' . "\0" . 'usuarioid', '' . "\0" . 'AppBundle\\Entity\\CeAcuerdoextraordinario' . "\0" . 'estatusextraordinarioid', '' . "\0" . 'AppBundle\\Entity\\CeAcuerdoextraordinario' . "\0" . 'extraordinarioid', '' . "\0" . 'AppBundle\\Entity\\CeAcuerdoextraordinario' . "\0" . 'periodoregularizacionid', '' . "\0" . 'AppBundle\\Entity\\CeAcuerdoextraordinario' . "\0" . 'tipoextraordinarioid'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (CeAcuerdoextraordinario $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setIntento($intento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIntento', [$intento]);

        return parent::setIntento($intento);
    }

    /**
     * {@inheritDoc}
     */
    public function getIntento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIntento', []);

        return parent::getIntento();
    }

    /**
     * {@inheritDoc}
     */
    public function setCalificacion($calificacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCalificacion', [$calificacion]);

        return parent::setCalificacion($calificacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getCalificacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCalificacion', []);

        return parent::getCalificacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setCalificacionfinal($calificacionfinal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCalificacionfinal', [$calificacionfinal]);

        return parent::setCalificacionfinal($calificacionfinal);
    }

    /**
     * {@inheritDoc}
     */
    public function getCalificacionfinal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCalificacionfinal', []);

        return parent::getCalificacionfinal();
    }

    /**
     * {@inheritDoc}
     */
    public function getAcuerdoextraordinarioid()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getAcuerdoextraordinarioid();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAcuerdoextraordinarioid', []);

        return parent::getAcuerdoextraordinarioid();
    }

    /**
     * {@inheritDoc}
     */
    public function setAgendaextraordinarioid(\AppBundle\Entity\CeAgendaextraordinario $agendaextraordinarioid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAgendaextraordinarioid', [$agendaextraordinarioid]);

        return parent::setAgendaextraordinarioid($agendaextraordinarioid);
    }

    /**
     * {@inheritDoc}
     */
    public function getAgendaextraordinarioid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAgendaextraordinarioid', []);

        return parent::getAgendaextraordinarioid();
    }

    /**
     * {@inheritDoc}
     */
    public function setDocumentoporpagarid(\AppBundle\Entity\CjDocumentoporpagar $documentoporpagarid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDocumentoporpagarid', [$documentoporpagarid]);

        return parent::setDocumentoporpagarid($documentoporpagarid);
    }

    /**
     * {@inheritDoc}
     */
    public function getDocumentoporpagarid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDocumentoporpagarid', []);

        return parent::getDocumentoporpagarid();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuarioid(\AppBundle\Entity\Usuario $usuarioid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuarioid', [$usuarioid]);

        return parent::setUsuarioid($usuarioid);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuarioid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuarioid', []);

        return parent::getUsuarioid();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstatusextraordinarioid(\AppBundle\Entity\CeEstatusextraordinario $estatusextraordinarioid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstatusextraordinarioid', [$estatusextraordinarioid]);

        return parent::setEstatusextraordinarioid($estatusextraordinarioid);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstatusextraordinarioid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstatusextraordinarioid', []);

        return parent::getEstatusextraordinarioid();
    }

    /**
     * {@inheritDoc}
     */
    public function setExtraordinarioid(\AppBundle\Entity\CeExtraordinario $extraordinarioid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExtraordinarioid', [$extraordinarioid]);

        return parent::setExtraordinarioid($extraordinarioid);
    }

    /**
     * {@inheritDoc}
     */
    public function getExtraordinarioid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExtraordinarioid', []);

        return parent::getExtraordinarioid();
    }

    /**
     * {@inheritDoc}
     */
    public function setPeriodoregularizacionid(\AppBundle\Entity\CePeriodoregularizacion $periodoregularizacionid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPeriodoregularizacionid', [$periodoregularizacionid]);

        return parent::setPeriodoregularizacionid($periodoregularizacionid);
    }

    /**
     * {@inheritDoc}
     */
    public function getPeriodoregularizacionid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPeriodoregularizacionid', []);

        return parent::getPeriodoregularizacionid();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoextraordinarioid(\AppBundle\Entity\CeTipoextraordinario $tipoextraordinarioid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoextraordinarioid', [$tipoextraordinarioid]);

        return parent::setTipoextraordinarioid($tipoextraordinarioid);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoextraordinarioid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoextraordinarioid', []);

        return parent::getTipoextraordinarioid();
    }

}
