<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CeConfiguracionpantallacalificaciones extends \AppBundle\Entity\CeConfiguracionpantallacalificaciones implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\CeConfiguracionpantallacalificaciones' . "\0" . 'consultaportalpadres', '' . "\0" . 'AppBundle\\Entity\\CeConfiguracionpantallacalificaciones' . "\0" . 'boletaportalpadres', '' . "\0" . 'AppBundle\\Entity\\CeConfiguracionpantallacalificaciones' . "\0" . 'consultaapppadres', '' . "\0" . 'AppBundle\\Entity\\CeConfiguracionpantallacalificaciones' . "\0" . 'boletaapppadres', '' . "\0" . 'AppBundle\\Entity\\CeConfiguracionpantallacalificaciones' . "\0" . 'consultaportalalumnos', '' . "\0" . 'AppBundle\\Entity\\CeConfiguracionpantallacalificaciones' . "\0" . 'boletaportalalumnos', '' . "\0" . 'AppBundle\\Entity\\CeConfiguracionpantallacalificaciones' . "\0" . 'consultaappalumnos', '' . "\0" . 'AppBundle\\Entity\\CeConfiguracionpantallacalificaciones' . "\0" . 'boletaappalumnos', '' . "\0" . 'AppBundle\\Entity\\CeConfiguracionpantallacalificaciones' . "\0" . 'configuracionpantallacalificacionid', '' . "\0" . 'AppBundle\\Entity\\CeConfiguracionpantallacalificaciones' . "\0" . 'gradoid'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\CeConfiguracionpantallacalificaciones' . "\0" . 'consultaportalpadres', '' . "\0" . 'AppBundle\\Entity\\CeConfiguracionpantallacalificaciones' . "\0" . 'boletaportalpadres', '' . "\0" . 'AppBundle\\Entity\\CeConfiguracionpantallacalificaciones' . "\0" . 'consultaapppadres', '' . "\0" . 'AppBundle\\Entity\\CeConfiguracionpantallacalificaciones' . "\0" . 'boletaapppadres', '' . "\0" . 'AppBundle\\Entity\\CeConfiguracionpantallacalificaciones' . "\0" . 'consultaportalalumnos', '' . "\0" . 'AppBundle\\Entity\\CeConfiguracionpantallacalificaciones' . "\0" . 'boletaportalalumnos', '' . "\0" . 'AppBundle\\Entity\\CeConfiguracionpantallacalificaciones' . "\0" . 'consultaappalumnos', '' . "\0" . 'AppBundle\\Entity\\CeConfiguracionpantallacalificaciones' . "\0" . 'boletaappalumnos', '' . "\0" . 'AppBundle\\Entity\\CeConfiguracionpantallacalificaciones' . "\0" . 'configuracionpantallacalificacionid', '' . "\0" . 'AppBundle\\Entity\\CeConfiguracionpantallacalificaciones' . "\0" . 'gradoid'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (CeConfiguracionpantallacalificaciones $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setConsultaportalpadres($consultaportalpadres)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConsultaportalpadres', [$consultaportalpadres]);

        return parent::setConsultaportalpadres($consultaportalpadres);
    }

    /**
     * {@inheritDoc}
     */
    public function getConsultaportalpadres()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConsultaportalpadres', []);

        return parent::getConsultaportalpadres();
    }

    /**
     * {@inheritDoc}
     */
    public function setBoletaportalpadres($boletaportalpadres)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBoletaportalpadres', [$boletaportalpadres]);

        return parent::setBoletaportalpadres($boletaportalpadres);
    }

    /**
     * {@inheritDoc}
     */
    public function getBoletaportalpadres()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBoletaportalpadres', []);

        return parent::getBoletaportalpadres();
    }

    /**
     * {@inheritDoc}
     */
    public function setConsultaapppadres($consultaapppadres)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConsultaapppadres', [$consultaapppadres]);

        return parent::setConsultaapppadres($consultaapppadres);
    }

    /**
     * {@inheritDoc}
     */
    public function getConsultaapppadres()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConsultaapppadres', []);

        return parent::getConsultaapppadres();
    }

    /**
     * {@inheritDoc}
     */
    public function setBoletaapppadres($boletaapppadres)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBoletaapppadres', [$boletaapppadres]);

        return parent::setBoletaapppadres($boletaapppadres);
    }

    /**
     * {@inheritDoc}
     */
    public function getBoletaapppadres()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBoletaapppadres', []);

        return parent::getBoletaapppadres();
    }

    /**
     * {@inheritDoc}
     */
    public function setConsultaportalalumnos($consultaportalalumnos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConsultaportalalumnos', [$consultaportalalumnos]);

        return parent::setConsultaportalalumnos($consultaportalalumnos);
    }

    /**
     * {@inheritDoc}
     */
    public function getConsultaportalalumnos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConsultaportalalumnos', []);

        return parent::getConsultaportalalumnos();
    }

    /**
     * {@inheritDoc}
     */
    public function setBoletaportalalumnos($boletaportalalumnos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBoletaportalalumnos', [$boletaportalalumnos]);

        return parent::setBoletaportalalumnos($boletaportalalumnos);
    }

    /**
     * {@inheritDoc}
     */
    public function getBoletaportalalumnos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBoletaportalalumnos', []);

        return parent::getBoletaportalalumnos();
    }

    /**
     * {@inheritDoc}
     */
    public function setConsultaappalumnos($consultaappalumnos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConsultaappalumnos', [$consultaappalumnos]);

        return parent::setConsultaappalumnos($consultaappalumnos);
    }

    /**
     * {@inheritDoc}
     */
    public function getConsultaappalumnos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConsultaappalumnos', []);

        return parent::getConsultaappalumnos();
    }

    /**
     * {@inheritDoc}
     */
    public function setBoletaappalumnos($boletaappalumnos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBoletaappalumnos', [$boletaappalumnos]);

        return parent::setBoletaappalumnos($boletaappalumnos);
    }

    /**
     * {@inheritDoc}
     */
    public function getBoletaappalumnos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBoletaappalumnos', []);

        return parent::getBoletaappalumnos();
    }

    /**
     * {@inheritDoc}
     */
    public function getConfiguracionpantallacalificacionid()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getConfiguracionpantallacalificacionid();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConfiguracionpantallacalificacionid', []);

        return parent::getConfiguracionpantallacalificacionid();
    }

    /**
     * {@inheritDoc}
     */
    public function setGradoid(\AppBundle\Entity\Grado $gradoid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGradoid', [$gradoid]);

        return parent::setGradoid($gradoid);
    }

    /**
     * {@inheritDoc}
     */
    public function getGradoid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGradoid', []);

        return parent::getGradoid();
    }

}
