<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CeAlumnocicloportallerextra extends \AppBundle\Entity\CeAlumnocicloportallerextra implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\CeAlumnocicloportallerextra' . "\0" . 'fechavencimiento', '' . "\0" . 'AppBundle\\Entity\\CeAlumnocicloportallerextra' . "\0" . 'reglamento', '' . "\0" . 'AppBundle\\Entity\\CeAlumnocicloportallerextra' . "\0" . 'materialentregado', '' . "\0" . 'AppBundle\\Entity\\CeAlumnocicloportallerextra' . "\0" . 'fechapreregistro', '' . "\0" . 'AppBundle\\Entity\\CeAlumnocicloportallerextra' . "\0" . 'personaautorizo', '' . "\0" . 'AppBundle\\Entity\\CeAlumnocicloportallerextra' . "\0" . 'credencialentregada', '' . "\0" . 'AppBundle\\Entity\\CeAlumnocicloportallerextra' . "\0" . 'alumnocicloportallerextraid', '' . "\0" . 'AppBundle\\Entity\\CeAlumnocicloportallerextra' . "\0" . 'alumnoporcicloid', '' . "\0" . 'AppBundle\\Entity\\CeAlumnocicloportallerextra' . "\0" . 'tallerextraid', '' . "\0" . 'AppBundle\\Entity\\CeAlumnocicloportallerextra' . "\0" . 'tallerextraestatusinscripcionid', '' . "\0" . 'AppBundle\\Entity\\CeAlumnocicloportallerextra' . "\0" . 'documentoporpagarid', '' . "\0" . 'AppBundle\\Entity\\CeAlumnocicloportallerextra' . "\0" . 'usuarioid'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\CeAlumnocicloportallerextra' . "\0" . 'fechavencimiento', '' . "\0" . 'AppBundle\\Entity\\CeAlumnocicloportallerextra' . "\0" . 'reglamento', '' . "\0" . 'AppBundle\\Entity\\CeAlumnocicloportallerextra' . "\0" . 'materialentregado', '' . "\0" . 'AppBundle\\Entity\\CeAlumnocicloportallerextra' . "\0" . 'fechapreregistro', '' . "\0" . 'AppBundle\\Entity\\CeAlumnocicloportallerextra' . "\0" . 'personaautorizo', '' . "\0" . 'AppBundle\\Entity\\CeAlumnocicloportallerextra' . "\0" . 'credencialentregada', '' . "\0" . 'AppBundle\\Entity\\CeAlumnocicloportallerextra' . "\0" . 'alumnocicloportallerextraid', '' . "\0" . 'AppBundle\\Entity\\CeAlumnocicloportallerextra' . "\0" . 'alumnoporcicloid', '' . "\0" . 'AppBundle\\Entity\\CeAlumnocicloportallerextra' . "\0" . 'tallerextraid', '' . "\0" . 'AppBundle\\Entity\\CeAlumnocicloportallerextra' . "\0" . 'tallerextraestatusinscripcionid', '' . "\0" . 'AppBundle\\Entity\\CeAlumnocicloportallerextra' . "\0" . 'documentoporpagarid', '' . "\0" . 'AppBundle\\Entity\\CeAlumnocicloportallerextra' . "\0" . 'usuarioid'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (CeAlumnocicloportallerextra $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setFechavencimiento($fechavencimiento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechavencimiento', [$fechavencimiento]);

        return parent::setFechavencimiento($fechavencimiento);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechavencimiento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechavencimiento', []);

        return parent::getFechavencimiento();
    }

    /**
     * {@inheritDoc}
     */
    public function setReglamento($reglamento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReglamento', [$reglamento]);

        return parent::setReglamento($reglamento);
    }

    /**
     * {@inheritDoc}
     */
    public function getReglamento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReglamento', []);

        return parent::getReglamento();
    }

    /**
     * {@inheritDoc}
     */
    public function setMaterialentregado($materialentregado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMaterialentregado', [$materialentregado]);

        return parent::setMaterialentregado($materialentregado);
    }

    /**
     * {@inheritDoc}
     */
    public function getMaterialentregado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMaterialentregado', []);

        return parent::getMaterialentregado();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechapreregistro($fechapreregistro)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechapreregistro', [$fechapreregistro]);

        return parent::setFechapreregistro($fechapreregistro);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechapreregistro()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechapreregistro', []);

        return parent::getFechapreregistro();
    }

    /**
     * {@inheritDoc}
     */
    public function setPersonaautorizo($personaautorizo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPersonaautorizo', [$personaautorizo]);

        return parent::setPersonaautorizo($personaautorizo);
    }

    /**
     * {@inheritDoc}
     */
    public function getPersonaautorizo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPersonaautorizo', []);

        return parent::getPersonaautorizo();
    }

    /**
     * {@inheritDoc}
     */
    public function setCredencialentregada($credencialentregada)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCredencialentregada', [$credencialentregada]);

        return parent::setCredencialentregada($credencialentregada);
    }

    /**
     * {@inheritDoc}
     */
    public function getCredencialentregada()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCredencialentregada', []);

        return parent::getCredencialentregada();
    }

    /**
     * {@inheritDoc}
     */
    public function getAlumnocicloportallerextraid()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getAlumnocicloportallerextraid();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAlumnocicloportallerextraid', []);

        return parent::getAlumnocicloportallerextraid();
    }

    /**
     * {@inheritDoc}
     */
    public function setAlumnoporcicloid(\AppBundle\Entity\CeAlumnoporciclo $alumnoporcicloid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAlumnoporcicloid', [$alumnoporcicloid]);

        return parent::setAlumnoporcicloid($alumnoporcicloid);
    }

    /**
     * {@inheritDoc}
     */
    public function getAlumnoporcicloid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAlumnoporcicloid', []);

        return parent::getAlumnoporcicloid();
    }

    /**
     * {@inheritDoc}
     */
    public function setTallerextraid(\AppBundle\Entity\CeTallerextracurricular $tallerextraid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTallerextraid', [$tallerextraid]);

        return parent::setTallerextraid($tallerextraid);
    }

    /**
     * {@inheritDoc}
     */
    public function getTallerextraid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTallerextraid', []);

        return parent::getTallerextraid();
    }

    /**
     * {@inheritDoc}
     */
    public function setTallerextraestatusinscripcionid(\AppBundle\Entity\CeTallerextraestatusinscripcion $tallerextraestatusinscripcionid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTallerextraestatusinscripcionid', [$tallerextraestatusinscripcionid]);

        return parent::setTallerextraestatusinscripcionid($tallerextraestatusinscripcionid);
    }

    /**
     * {@inheritDoc}
     */
    public function getTallerextraestatusinscripcionid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTallerextraestatusinscripcionid', []);

        return parent::getTallerextraestatusinscripcionid();
    }

    /**
     * {@inheritDoc}
     */
    public function setDocumentoporpagarid(\AppBundle\Entity\CjDocumentoporpagar $documentoporpagarid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDocumentoporpagarid', [$documentoporpagarid]);

        return parent::setDocumentoporpagarid($documentoporpagarid);
    }

    /**
     * {@inheritDoc}
     */
    public function getDocumentoporpagarid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDocumentoporpagarid', []);

        return parent::getDocumentoporpagarid();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuarioid(\AppBundle\Entity\Usuario $usuarioid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuarioid', [$usuarioid]);

        return parent::setUsuarioid($usuarioid);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuarioid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuarioid', []);

        return parent::getUsuarioid();
    }

}
