<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class BcOtrosdependienteseconomicos extends \AppBundle\Entity\BcOtrosdependienteseconomicos implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\BcOtrosdependienteseconomicos' . "\0" . 'nombrecompleto', '' . "\0" . 'AppBundle\\Entity\\BcOtrosdependienteseconomicos' . "\0" . 'relacion', '' . "\0" . 'AppBundle\\Entity\\BcOtrosdependienteseconomicos' . "\0" . 'ocupacion', '' . "\0" . 'AppBundle\\Entity\\BcOtrosdependienteseconomicos' . "\0" . 'edad', '' . "\0" . 'AppBundle\\Entity\\BcOtrosdependienteseconomicos' . "\0" . 'otrosdependientesid', '' . "\0" . 'AppBundle\\Entity\\BcOtrosdependienteseconomicos' . "\0" . 'situacionconyugalid', '' . "\0" . 'AppBundle\\Entity\\BcOtrosdependienteseconomicos' . "\0" . 'solicitudid'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\BcOtrosdependienteseconomicos' . "\0" . 'nombrecompleto', '' . "\0" . 'AppBundle\\Entity\\BcOtrosdependienteseconomicos' . "\0" . 'relacion', '' . "\0" . 'AppBundle\\Entity\\BcOtrosdependienteseconomicos' . "\0" . 'ocupacion', '' . "\0" . 'AppBundle\\Entity\\BcOtrosdependienteseconomicos' . "\0" . 'edad', '' . "\0" . 'AppBundle\\Entity\\BcOtrosdependienteseconomicos' . "\0" . 'otrosdependientesid', '' . "\0" . 'AppBundle\\Entity\\BcOtrosdependienteseconomicos' . "\0" . 'situacionconyugalid', '' . "\0" . 'AppBundle\\Entity\\BcOtrosdependienteseconomicos' . "\0" . 'solicitudid'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (BcOtrosdependienteseconomicos $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setNombrecompleto($nombrecompleto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombrecompleto', [$nombrecompleto]);

        return parent::setNombrecompleto($nombrecompleto);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombrecompleto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombrecompleto', []);

        return parent::getNombrecompleto();
    }

    /**
     * {@inheritDoc}
     */
    public function setRelacion($relacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRelacion', [$relacion]);

        return parent::setRelacion($relacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getRelacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRelacion', []);

        return parent::getRelacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setOcupacion($ocupacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOcupacion', [$ocupacion]);

        return parent::setOcupacion($ocupacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getOcupacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOcupacion', []);

        return parent::getOcupacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setEdad($edad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEdad', [$edad]);

        return parent::setEdad($edad);
    }

    /**
     * {@inheritDoc}
     */
    public function getEdad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEdad', []);

        return parent::getEdad();
    }

    /**
     * {@inheritDoc}
     */
    public function getOtrosdependientesid()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getOtrosdependientesid();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOtrosdependientesid', []);

        return parent::getOtrosdependientesid();
    }

    /**
     * {@inheritDoc}
     */
    public function setSituacionconyugalid(\AppBundle\Entity\Situacionconyugal $situacionconyugalid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSituacionconyugalid', [$situacionconyugalid]);

        return parent::setSituacionconyugalid($situacionconyugalid);
    }

    /**
     * {@inheritDoc}
     */
    public function getSituacionconyugalid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSituacionconyugalid', []);

        return parent::getSituacionconyugalid();
    }

    /**
     * {@inheritDoc}
     */
    public function setSolicitudid(\AppBundle\Entity\BcSolicitudbeca $solicitudid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSolicitudid', [$solicitudid]);

        return parent::setSolicitudid($solicitudid);
    }

    /**
     * {@inheritDoc}
     */
    public function getSolicitudid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSolicitudid', []);

        return parent::getSolicitudid();
    }

}
