<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Lugar extends \AppBundle\Entity\Lugar implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Lugar' . "\0" . 'nombre', '' . "\0" . 'AppBundle\\Entity\\Lugar' . "\0" . 'cupo', '' . "\0" . 'AppBundle\\Entity\\Lugar' . "\0" . 'equipocomputo', '' . "\0" . 'AppBundle\\Entity\\Lugar' . "\0" . 'equipocantidad', '' . "\0" . 'AppBundle\\Entity\\Lugar' . "\0" . 'proyector', '' . "\0" . 'AppBundle\\Entity\\Lugar' . "\0" . 'internet', '' . "\0" . 'AppBundle\\Entity\\Lugar' . "\0" . 'activo', '' . "\0" . 'AppBundle\\Entity\\Lugar' . "\0" . 'lugarid', '' . "\0" . 'AppBundle\\Entity\\Lugar' . "\0" . 'edificioid'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Lugar' . "\0" . 'nombre', '' . "\0" . 'AppBundle\\Entity\\Lugar' . "\0" . 'cupo', '' . "\0" . 'AppBundle\\Entity\\Lugar' . "\0" . 'equipocomputo', '' . "\0" . 'AppBundle\\Entity\\Lugar' . "\0" . 'equipocantidad', '' . "\0" . 'AppBundle\\Entity\\Lugar' . "\0" . 'proyector', '' . "\0" . 'AppBundle\\Entity\\Lugar' . "\0" . 'internet', '' . "\0" . 'AppBundle\\Entity\\Lugar' . "\0" . 'activo', '' . "\0" . 'AppBundle\\Entity\\Lugar' . "\0" . 'lugarid', '' . "\0" . 'AppBundle\\Entity\\Lugar' . "\0" . 'edificioid'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Lugar $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', [$nombre]);

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', []);

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setCupo($cupo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCupo', [$cupo]);

        return parent::setCupo($cupo);
    }

    /**
     * {@inheritDoc}
     */
    public function getCupo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCupo', []);

        return parent::getCupo();
    }

    /**
     * {@inheritDoc}
     */
    public function setEquipocomputo($equipocomputo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEquipocomputo', [$equipocomputo]);

        return parent::setEquipocomputo($equipocomputo);
    }

    /**
     * {@inheritDoc}
     */
    public function getEquipocomputo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEquipocomputo', []);

        return parent::getEquipocomputo();
    }

    /**
     * {@inheritDoc}
     */
    public function setEquipocantidad($equipocantidad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEquipocantidad', [$equipocantidad]);

        return parent::setEquipocantidad($equipocantidad);
    }

    /**
     * {@inheritDoc}
     */
    public function getEquipocantidad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEquipocantidad', []);

        return parent::getEquipocantidad();
    }

    /**
     * {@inheritDoc}
     */
    public function setProyector($proyector)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProyector', [$proyector]);

        return parent::setProyector($proyector);
    }

    /**
     * {@inheritDoc}
     */
    public function getProyector()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProyector', []);

        return parent::getProyector();
    }

    /**
     * {@inheritDoc}
     */
    public function setInternet($internet)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInternet', [$internet]);

        return parent::setInternet($internet);
    }

    /**
     * {@inheritDoc}
     */
    public function getInternet()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInternet', []);

        return parent::getInternet();
    }

    /**
     * {@inheritDoc}
     */
    public function setActivo($activo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActivo', [$activo]);

        return parent::setActivo($activo);
    }

    /**
     * {@inheritDoc}
     */
    public function getActivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActivo', []);

        return parent::getActivo();
    }

    /**
     * {@inheritDoc}
     */
    public function getLugarid()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getLugarid();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLugarid', []);

        return parent::getLugarid();
    }

    /**
     * {@inheritDoc}
     */
    public function setEdificioid(\AppBundle\Entity\Edificio $edificioid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEdificioid', [$edificioid]);

        return parent::setEdificioid($edificioid);
    }

    /**
     * {@inheritDoc}
     */
    public function getEdificioid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEdificioid', []);

        return parent::getEdificioid();
    }

}
