<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class BcDomicilioestudiosocioeconomico extends \AppBundle\Entity\BcDomicilioestudiosocioeconomico implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\BcDomicilioestudiosocioeconomico' . "\0" . 'codigopostal', '' . "\0" . 'AppBundle\\Entity\\BcDomicilioestudiosocioeconomico' . "\0" . 'calle', '' . "\0" . 'AppBundle\\Entity\\BcDomicilioestudiosocioeconomico' . "\0" . 'numeroexterior', '' . "\0" . 'AppBundle\\Entity\\BcDomicilioestudiosocioeconomico' . "\0" . 'numerointerior', '' . "\0" . 'AppBundle\\Entity\\BcDomicilioestudiosocioeconomico' . "\0" . 'otracolonia', '' . "\0" . 'AppBundle\\Entity\\BcDomicilioestudiosocioeconomico' . "\0" . 'entrecalles', '' . "\0" . 'AppBundle\\Entity\\BcDomicilioestudiosocioeconomico' . "\0" . 'telefonocasa', '' . "\0" . 'AppBundle\\Entity\\BcDomicilioestudiosocioeconomico' . "\0" . 'domicilioestudiosocioeconomicoid', '' . "\0" . 'AppBundle\\Entity\\BcDomicilioestudiosocioeconomico' . "\0" . 'estadoid', '' . "\0" . 'AppBundle\\Entity\\BcDomicilioestudiosocioeconomico' . "\0" . 'municipioid', '' . "\0" . 'AppBundle\\Entity\\BcDomicilioestudiosocioeconomico' . "\0" . 'solicitudid', '' . "\0" . 'AppBundle\\Entity\\BcDomicilioestudiosocioeconomico' . "\0" . 'coloniaid', '' . "\0" . 'AppBundle\\Entity\\BcDomicilioestudiosocioeconomico' . "\0" . 'paisid'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\BcDomicilioestudiosocioeconomico' . "\0" . 'codigopostal', '' . "\0" . 'AppBundle\\Entity\\BcDomicilioestudiosocioeconomico' . "\0" . 'calle', '' . "\0" . 'AppBundle\\Entity\\BcDomicilioestudiosocioeconomico' . "\0" . 'numeroexterior', '' . "\0" . 'AppBundle\\Entity\\BcDomicilioestudiosocioeconomico' . "\0" . 'numerointerior', '' . "\0" . 'AppBundle\\Entity\\BcDomicilioestudiosocioeconomico' . "\0" . 'otracolonia', '' . "\0" . 'AppBundle\\Entity\\BcDomicilioestudiosocioeconomico' . "\0" . 'entrecalles', '' . "\0" . 'AppBundle\\Entity\\BcDomicilioestudiosocioeconomico' . "\0" . 'telefonocasa', '' . "\0" . 'AppBundle\\Entity\\BcDomicilioestudiosocioeconomico' . "\0" . 'domicilioestudiosocioeconomicoid', '' . "\0" . 'AppBundle\\Entity\\BcDomicilioestudiosocioeconomico' . "\0" . 'estadoid', '' . "\0" . 'AppBundle\\Entity\\BcDomicilioestudiosocioeconomico' . "\0" . 'municipioid', '' . "\0" . 'AppBundle\\Entity\\BcDomicilioestudiosocioeconomico' . "\0" . 'solicitudid', '' . "\0" . 'AppBundle\\Entity\\BcDomicilioestudiosocioeconomico' . "\0" . 'coloniaid', '' . "\0" . 'AppBundle\\Entity\\BcDomicilioestudiosocioeconomico' . "\0" . 'paisid'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (BcDomicilioestudiosocioeconomico $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setCodigopostal($codigopostal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodigopostal', [$codigopostal]);

        return parent::setCodigopostal($codigopostal);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodigopostal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodigopostal', []);

        return parent::getCodigopostal();
    }

    /**
     * {@inheritDoc}
     */
    public function setCalle($calle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCalle', [$calle]);

        return parent::setCalle($calle);
    }

    /**
     * {@inheritDoc}
     */
    public function getCalle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCalle', []);

        return parent::getCalle();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroexterior($numeroexterior)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroexterior', [$numeroexterior]);

        return parent::setNumeroexterior($numeroexterior);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroexterior()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroexterior', []);

        return parent::getNumeroexterior();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumerointerior($numerointerior)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumerointerior', [$numerointerior]);

        return parent::setNumerointerior($numerointerior);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumerointerior()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumerointerior', []);

        return parent::getNumerointerior();
    }

    /**
     * {@inheritDoc}
     */
    public function setOtracolonia($otracolonia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOtracolonia', [$otracolonia]);

        return parent::setOtracolonia($otracolonia);
    }

    /**
     * {@inheritDoc}
     */
    public function getOtracolonia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOtracolonia', []);

        return parent::getOtracolonia();
    }

    /**
     * {@inheritDoc}
     */
    public function setEntrecalles($entrecalles)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEntrecalles', [$entrecalles]);

        return parent::setEntrecalles($entrecalles);
    }

    /**
     * {@inheritDoc}
     */
    public function getEntrecalles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEntrecalles', []);

        return parent::getEntrecalles();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefonocasa($telefonocasa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefonocasa', [$telefonocasa]);

        return parent::setTelefonocasa($telefonocasa);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefonocasa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefonocasa', []);

        return parent::getTelefonocasa();
    }

    /**
     * {@inheritDoc}
     */
    public function getDomicilioestudiosocioeconomicoid()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getDomicilioestudiosocioeconomicoid();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDomicilioestudiosocioeconomicoid', []);

        return parent::getDomicilioestudiosocioeconomicoid();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstadoid(\AppBundle\Entity\Estado $estadoid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstadoid', [$estadoid]);

        return parent::setEstadoid($estadoid);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstadoid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstadoid', []);

        return parent::getEstadoid();
    }

    /**
     * {@inheritDoc}
     */
    public function setMunicipioid(\AppBundle\Entity\Municipio $municipioid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMunicipioid', [$municipioid]);

        return parent::setMunicipioid($municipioid);
    }

    /**
     * {@inheritDoc}
     */
    public function getMunicipioid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMunicipioid', []);

        return parent::getMunicipioid();
    }

    /**
     * {@inheritDoc}
     */
    public function setSolicitudid(\AppBundle\Entity\BcSolicitudbeca $solicitudid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSolicitudid', [$solicitudid]);

        return parent::setSolicitudid($solicitudid);
    }

    /**
     * {@inheritDoc}
     */
    public function getSolicitudid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSolicitudid', []);

        return parent::getSolicitudid();
    }

    /**
     * {@inheritDoc}
     */
    public function setColoniaid(\AppBundle\Entity\Colonia $coloniaid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setColoniaid', [$coloniaid]);

        return parent::setColoniaid($coloniaid);
    }

    /**
     * {@inheritDoc}
     */
    public function getColoniaid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getColoniaid', []);

        return parent::getColoniaid();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaisid(\AppBundle\Entity\Pais $paisid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaisid', [$paisid]);

        return parent::setPaisid($paisid);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaisid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaisid', []);

        return parent::getPaisid();
    }

}
