<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Pregunta extends \AppBundle\Entity\Pregunta implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Pregunta' . "\0" . 'pregunta', '' . "\0" . 'AppBundle\\Entity\\Pregunta' . "\0" . 'valorporcentaje', '' . "\0" . 'AppBundle\\Entity\\Pregunta' . "\0" . 'tipoordenamiento', '' . "\0" . 'AppBundle\\Entity\\Pregunta' . "\0" . 'anidada', '' . "\0" . 'AppBundle\\Entity\\Pregunta' . "\0" . 'resaltar', '' . "\0" . 'AppBundle\\Entity\\Pregunta' . "\0" . 'color', '' . "\0" . 'AppBundle\\Entity\\Pregunta' . "\0" . 'validar', '' . "\0" . 'AppBundle\\Entity\\Pregunta' . "\0" . 'preguntaid', '' . "\0" . 'AppBundle\\Entity\\Pregunta' . "\0" . 'padreid', '' . "\0" . 'AppBundle\\Entity\\Pregunta' . "\0" . 'tipopreguntaid'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Pregunta' . "\0" . 'pregunta', '' . "\0" . 'AppBundle\\Entity\\Pregunta' . "\0" . 'valorporcentaje', '' . "\0" . 'AppBundle\\Entity\\Pregunta' . "\0" . 'tipoordenamiento', '' . "\0" . 'AppBundle\\Entity\\Pregunta' . "\0" . 'anidada', '' . "\0" . 'AppBundle\\Entity\\Pregunta' . "\0" . 'resaltar', '' . "\0" . 'AppBundle\\Entity\\Pregunta' . "\0" . 'color', '' . "\0" . 'AppBundle\\Entity\\Pregunta' . "\0" . 'validar', '' . "\0" . 'AppBundle\\Entity\\Pregunta' . "\0" . 'preguntaid', '' . "\0" . 'AppBundle\\Entity\\Pregunta' . "\0" . 'padreid', '' . "\0" . 'AppBundle\\Entity\\Pregunta' . "\0" . 'tipopreguntaid'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Pregunta $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setPregunta($pregunta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPregunta', [$pregunta]);

        return parent::setPregunta($pregunta);
    }

    /**
     * {@inheritDoc}
     */
    public function getPregunta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPregunta', []);

        return parent::getPregunta();
    }

    /**
     * {@inheritDoc}
     */
    public function setValorporcentaje($valorporcentaje)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValorporcentaje', [$valorporcentaje]);

        return parent::setValorporcentaje($valorporcentaje);
    }

    /**
     * {@inheritDoc}
     */
    public function getValorporcentaje()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValorporcentaje', []);

        return parent::getValorporcentaje();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoordenamiento($tipoordenamiento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoordenamiento', [$tipoordenamiento]);

        return parent::setTipoordenamiento($tipoordenamiento);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoordenamiento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoordenamiento', []);

        return parent::getTipoordenamiento();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnidada($anidada)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnidada', [$anidada]);

        return parent::setAnidada($anidada);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnidada()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnidada', []);

        return parent::getAnidada();
    }

    /**
     * {@inheritDoc}
     */
    public function setResaltar($resaltar)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResaltar', [$resaltar]);

        return parent::setResaltar($resaltar);
    }

    /**
     * {@inheritDoc}
     */
    public function getResaltar()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResaltar', []);

        return parent::getResaltar();
    }

    /**
     * {@inheritDoc}
     */
    public function setColor($color)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setColor', [$color]);

        return parent::setColor($color);
    }

    /**
     * {@inheritDoc}
     */
    public function getColor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getColor', []);

        return parent::getColor();
    }

    /**
     * {@inheritDoc}
     */
    public function setValidar($validar)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValidar', [$validar]);

        return parent::setValidar($validar);
    }

    /**
     * {@inheritDoc}
     */
    public function getValidar()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValidar', []);

        return parent::getValidar();
    }

    /**
     * {@inheritDoc}
     */
    public function getPreguntaid()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getPreguntaid();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPreguntaid', []);

        return parent::getPreguntaid();
    }

    /**
     * {@inheritDoc}
     */
    public function setPadreid(\AppBundle\Entity\Respuesta $padreid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPadreid', [$padreid]);

        return parent::setPadreid($padreid);
    }

    /**
     * {@inheritDoc}
     */
    public function getPadreid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPadreid', []);

        return parent::getPadreid();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipopreguntaid(\AppBundle\Entity\Tipopregunta $tipopreguntaid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipopreguntaid', [$tipopreguntaid]);

        return parent::setTipopreguntaid($tipopreguntaid);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipopreguntaid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipopreguntaid', []);

        return parent::getTipopreguntaid();
    }

}
