<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CjDevolucion extends \AppBundle\Entity\CjDevolucion implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\CjDevolucion' . "\0" . 'usuarioidautoriza', '' . "\0" . 'AppBundle\\Entity\\CjDevolucion' . "\0" . 'personarecibedinero', '' . "\0" . 'AppBundle\\Entity\\CjDevolucion' . "\0" . 'motivo', '' . "\0" . 'AppBundle\\Entity\\CjDevolucion' . "\0" . 'monto', '' . "\0" . 'AppBundle\\Entity\\CjDevolucion' . "\0" . 'fecha', '' . "\0" . 'AppBundle\\Entity\\CjDevolucion' . "\0" . 'facturado', '' . "\0" . 'AppBundle\\Entity\\CjDevolucion' . "\0" . 'devolucionid', '' . "\0" . 'AppBundle\\Entity\\CjDevolucion' . "\0" . 'bitacoracajaid', '' . "\0" . 'AppBundle\\Entity\\CjDevolucion' . "\0" . 'cajaid', '' . "\0" . 'AppBundle\\Entity\\CjDevolucion' . "\0" . 'empresaid', '' . "\0" . 'AppBundle\\Entity\\CjDevolucion' . "\0" . 'padresotutoresid', '' . "\0" . 'AppBundle\\Entity\\CjDevolucion' . "\0" . 'pagoid', '' . "\0" . 'AppBundle\\Entity\\CjDevolucion' . "\0" . 'usuarioid'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\CjDevolucion' . "\0" . 'usuarioidautoriza', '' . "\0" . 'AppBundle\\Entity\\CjDevolucion' . "\0" . 'personarecibedinero', '' . "\0" . 'AppBundle\\Entity\\CjDevolucion' . "\0" . 'motivo', '' . "\0" . 'AppBundle\\Entity\\CjDevolucion' . "\0" . 'monto', '' . "\0" . 'AppBundle\\Entity\\CjDevolucion' . "\0" . 'fecha', '' . "\0" . 'AppBundle\\Entity\\CjDevolucion' . "\0" . 'facturado', '' . "\0" . 'AppBundle\\Entity\\CjDevolucion' . "\0" . 'devolucionid', '' . "\0" . 'AppBundle\\Entity\\CjDevolucion' . "\0" . 'bitacoracajaid', '' . "\0" . 'AppBundle\\Entity\\CjDevolucion' . "\0" . 'cajaid', '' . "\0" . 'AppBundle\\Entity\\CjDevolucion' . "\0" . 'empresaid', '' . "\0" . 'AppBundle\\Entity\\CjDevolucion' . "\0" . 'padresotutoresid', '' . "\0" . 'AppBundle\\Entity\\CjDevolucion' . "\0" . 'pagoid', '' . "\0" . 'AppBundle\\Entity\\CjDevolucion' . "\0" . 'usuarioid'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (CjDevolucion $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setUsuarioidautoriza($usuarioidautoriza)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuarioidautoriza', [$usuarioidautoriza]);

        return parent::setUsuarioidautoriza($usuarioidautoriza);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuarioidautoriza()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuarioidautoriza', []);

        return parent::getUsuarioidautoriza();
    }

    /**
     * {@inheritDoc}
     */
    public function setPersonarecibedinero($personarecibedinero)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPersonarecibedinero', [$personarecibedinero]);

        return parent::setPersonarecibedinero($personarecibedinero);
    }

    /**
     * {@inheritDoc}
     */
    public function getPersonarecibedinero()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPersonarecibedinero', []);

        return parent::getPersonarecibedinero();
    }

    /**
     * {@inheritDoc}
     */
    public function setMotivo($motivo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMotivo', [$motivo]);

        return parent::setMotivo($motivo);
    }

    /**
     * {@inheritDoc}
     */
    public function getMotivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMotivo', []);

        return parent::getMotivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setMonto($monto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMonto', [$monto]);

        return parent::setMonto($monto);
    }

    /**
     * {@inheritDoc}
     */
    public function getMonto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMonto', []);

        return parent::getMonto();
    }

    /**
     * {@inheritDoc}
     */
    public function setFecha($fecha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFecha', [$fecha]);

        return parent::setFecha($fecha);
    }

    /**
     * {@inheritDoc}
     */
    public function getFecha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFecha', []);

        return parent::getFecha();
    }

    /**
     * {@inheritDoc}
     */
    public function setFacturado($facturado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFacturado', [$facturado]);

        return parent::setFacturado($facturado);
    }

    /**
     * {@inheritDoc}
     */
    public function getFacturado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFacturado', []);

        return parent::getFacturado();
    }

    /**
     * {@inheritDoc}
     */
    public function getDevolucionid()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getDevolucionid();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDevolucionid', []);

        return parent::getDevolucionid();
    }

    /**
     * {@inheritDoc}
     */
    public function setBitacoracajaid(\AppBundle\Entity\CjBitacoracaja $bitacoracajaid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBitacoracajaid', [$bitacoracajaid]);

        return parent::setBitacoracajaid($bitacoracajaid);
    }

    /**
     * {@inheritDoc}
     */
    public function getBitacoracajaid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBitacoracajaid', []);

        return parent::getBitacoracajaid();
    }

    /**
     * {@inheritDoc}
     */
    public function setCajaid(\AppBundle\Entity\CjCaja $cajaid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCajaid', [$cajaid]);

        return parent::setCajaid($cajaid);
    }

    /**
     * {@inheritDoc}
     */
    public function getCajaid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCajaid', []);

        return parent::getCajaid();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmpresaid(\AppBundle\Entity\CjEmpresa $empresaid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmpresaid', [$empresaid]);

        return parent::setEmpresaid($empresaid);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmpresaid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmpresaid', []);

        return parent::getEmpresaid();
    }

    /**
     * {@inheritDoc}
     */
    public function setPadresotutoresid(\AppBundle\Entity\CePadresotutores $padresotutoresid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPadresotutoresid', [$padresotutoresid]);

        return parent::setPadresotutoresid($padresotutoresid);
    }

    /**
     * {@inheritDoc}
     */
    public function getPadresotutoresid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPadresotutoresid', []);

        return parent::getPadresotutoresid();
    }

    /**
     * {@inheritDoc}
     */
    public function setPagoid(\AppBundle\Entity\CjPago $pagoid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPagoid', [$pagoid]);

        return parent::setPagoid($pagoid);
    }

    /**
     * {@inheritDoc}
     */
    public function getPagoid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPagoid', []);

        return parent::getPagoid();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuarioid(\AppBundle\Entity\Usuario $usuarioid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuarioid', [$usuarioid]);

        return parent::setUsuarioid($usuarioid);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuarioid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuarioid', []);

        return parent::getUsuarioid();
    }

}
