<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class TpBoletobitacora extends \AppBundle\Entity\TpBoletobitacora implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\TpBoletobitacora' . "\0" . 'boletoid', '' . "\0" . 'AppBundle\\Entity\\TpBoletobitacora' . "\0" . 'fechaviaje', '' . "\0" . 'AppBundle\\Entity\\TpBoletobitacora' . "\0" . 'fechacompra', '' . "\0" . 'AppBundle\\Entity\\TpBoletobitacora' . "\0" . 'fechaedicion', '' . "\0" . 'AppBundle\\Entity\\TpBoletobitacora' . "\0" . 'medioedicion', '' . "\0" . 'AppBundle\\Entity\\TpBoletobitacora' . "\0" . 'usuarioedicion', '' . "\0" . 'AppBundle\\Entity\\TpBoletobitacora' . "\0" . 'fechacancelacion', '' . "\0" . 'AppBundle\\Entity\\TpBoletobitacora' . "\0" . 'mediocancelacion', '' . "\0" . 'AppBundle\\Entity\\TpBoletobitacora' . "\0" . 'usuariocancelacion', '' . "\0" . 'AppBundle\\Entity\\TpBoletobitacora' . "\0" . 'precio', '' . "\0" . 'AppBundle\\Entity\\TpBoletobitacora' . "\0" . 'usuario', '' . "\0" . 'AppBundle\\Entity\\TpBoletobitacora' . "\0" . 'portal', '' . "\0" . 'AppBundle\\Entity\\TpBoletobitacora' . "\0" . 'escaneado', '' . "\0" . 'AppBundle\\Entity\\TpBoletobitacora' . "\0" . 'boletobitacoraid', '' . "\0" . 'AppBundle\\Entity\\TpBoletobitacora' . "\0" . 'alumnoid', '' . "\0" . 'AppBundle\\Entity\\TpBoletobitacora' . "\0" . 'boletoestatusid', '' . "\0" . 'AppBundle\\Entity\\TpBoletobitacora' . "\0" . 'paradaid', '' . "\0" . 'AppBundle\\Entity\\TpBoletobitacora' . "\0" . 'rutaid'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\TpBoletobitacora' . "\0" . 'boletoid', '' . "\0" . 'AppBundle\\Entity\\TpBoletobitacora' . "\0" . 'fechaviaje', '' . "\0" . 'AppBundle\\Entity\\TpBoletobitacora' . "\0" . 'fechacompra', '' . "\0" . 'AppBundle\\Entity\\TpBoletobitacora' . "\0" . 'fechaedicion', '' . "\0" . 'AppBundle\\Entity\\TpBoletobitacora' . "\0" . 'medioedicion', '' . "\0" . 'AppBundle\\Entity\\TpBoletobitacora' . "\0" . 'usuarioedicion', '' . "\0" . 'AppBundle\\Entity\\TpBoletobitacora' . "\0" . 'fechacancelacion', '' . "\0" . 'AppBundle\\Entity\\TpBoletobitacora' . "\0" . 'mediocancelacion', '' . "\0" . 'AppBundle\\Entity\\TpBoletobitacora' . "\0" . 'usuariocancelacion', '' . "\0" . 'AppBundle\\Entity\\TpBoletobitacora' . "\0" . 'precio', '' . "\0" . 'AppBundle\\Entity\\TpBoletobitacora' . "\0" . 'usuario', '' . "\0" . 'AppBundle\\Entity\\TpBoletobitacora' . "\0" . 'portal', '' . "\0" . 'AppBundle\\Entity\\TpBoletobitacora' . "\0" . 'escaneado', '' . "\0" . 'AppBundle\\Entity\\TpBoletobitacora' . "\0" . 'boletobitacoraid', '' . "\0" . 'AppBundle\\Entity\\TpBoletobitacora' . "\0" . 'alumnoid', '' . "\0" . 'AppBundle\\Entity\\TpBoletobitacora' . "\0" . 'boletoestatusid', '' . "\0" . 'AppBundle\\Entity\\TpBoletobitacora' . "\0" . 'paradaid', '' . "\0" . 'AppBundle\\Entity\\TpBoletobitacora' . "\0" . 'rutaid'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (TpBoletobitacora $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setBoletoid($boletoid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBoletoid', [$boletoid]);

        return parent::setBoletoid($boletoid);
    }

    /**
     * {@inheritDoc}
     */
    public function getBoletoid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBoletoid', []);

        return parent::getBoletoid();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaviaje($fechaviaje)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaviaje', [$fechaviaje]);

        return parent::setFechaviaje($fechaviaje);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaviaje()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaviaje', []);

        return parent::getFechaviaje();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechacompra($fechacompra)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechacompra', [$fechacompra]);

        return parent::setFechacompra($fechacompra);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechacompra()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechacompra', []);

        return parent::getFechacompra();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaedicion($fechaedicion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaedicion', [$fechaedicion]);

        return parent::setFechaedicion($fechaedicion);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaedicion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaedicion', []);

        return parent::getFechaedicion();
    }

    /**
     * {@inheritDoc}
     */
    public function setMedioedicion($medioedicion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMedioedicion', [$medioedicion]);

        return parent::setMedioedicion($medioedicion);
    }

    /**
     * {@inheritDoc}
     */
    public function getMedioedicion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMedioedicion', []);

        return parent::getMedioedicion();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuarioedicion($usuarioedicion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuarioedicion', [$usuarioedicion]);

        return parent::setUsuarioedicion($usuarioedicion);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuarioedicion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuarioedicion', []);

        return parent::getUsuarioedicion();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechacancelacion($fechacancelacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechacancelacion', [$fechacancelacion]);

        return parent::setFechacancelacion($fechacancelacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechacancelacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechacancelacion', []);

        return parent::getFechacancelacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setMediocancelacion($mediocancelacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMediocancelacion', [$mediocancelacion]);

        return parent::setMediocancelacion($mediocancelacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getMediocancelacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMediocancelacion', []);

        return parent::getMediocancelacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuariocancelacion($usuariocancelacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuariocancelacion', [$usuariocancelacion]);

        return parent::setUsuariocancelacion($usuariocancelacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuariocancelacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuariocancelacion', []);

        return parent::getUsuariocancelacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrecio($precio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrecio', [$precio]);

        return parent::setPrecio($precio);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrecio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrecio', []);

        return parent::getPrecio();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuario($usuario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuario', [$usuario]);

        return parent::setUsuario($usuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuario', []);

        return parent::getUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setPortal($portal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPortal', [$portal]);

        return parent::setPortal($portal);
    }

    /**
     * {@inheritDoc}
     */
    public function getPortal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPortal', []);

        return parent::getPortal();
    }

    /**
     * {@inheritDoc}
     */
    public function setEscaneado($escaneado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEscaneado', [$escaneado]);

        return parent::setEscaneado($escaneado);
    }

    /**
     * {@inheritDoc}
     */
    public function getEscaneado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEscaneado', []);

        return parent::getEscaneado();
    }

    /**
     * {@inheritDoc}
     */
    public function getBoletobitacoraid()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getBoletobitacoraid();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBoletobitacoraid', []);

        return parent::getBoletobitacoraid();
    }

    /**
     * {@inheritDoc}
     */
    public function setAlumnoid(\AppBundle\Entity\CeAlumno $alumnoid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAlumnoid', [$alumnoid]);

        return parent::setAlumnoid($alumnoid);
    }

    /**
     * {@inheritDoc}
     */
    public function getAlumnoid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAlumnoid', []);

        return parent::getAlumnoid();
    }

    /**
     * {@inheritDoc}
     */
    public function setBoletoestatusid(\AppBundle\Entity\TpBoletoestatus $boletoestatusid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBoletoestatusid', [$boletoestatusid]);

        return parent::setBoletoestatusid($boletoestatusid);
    }

    /**
     * {@inheritDoc}
     */
    public function getBoletoestatusid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBoletoestatusid', []);

        return parent::getBoletoestatusid();
    }

    /**
     * {@inheritDoc}
     */
    public function setParadaid(\AppBundle\Entity\TpRutaprecioparada $paradaid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParadaid', [$paradaid]);

        return parent::setParadaid($paradaid);
    }

    /**
     * {@inheritDoc}
     */
    public function getParadaid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParadaid', []);

        return parent::getParadaid();
    }

    /**
     * {@inheritDoc}
     */
    public function setRutaid(\AppBundle\Entity\TpRuta $rutaid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRutaid', [$rutaid]);

        return parent::setRutaid($rutaid);
    }

    /**
     * {@inheritDoc}
     */
    public function getRutaid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRutaid', []);

        return parent::getRutaid();
    }

}
