<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Infoadicional extends \AppBundle\Entity\Infoadicional implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Infoadicional' . "\0" . 'estadosalud', '' . "\0" . 'AppBundle\\Entity\\Infoadicional' . "\0" . 'aspectosinportantes', '' . "\0" . 'AppBundle\\Entity\\Infoadicional' . "\0" . 'necesidadespecial', '' . "\0" . 'AppBundle\\Entity\\Infoadicional' . "\0" . 'descripcionnecesidad', '' . "\0" . 'AppBundle\\Entity\\Infoadicional' . "\0" . 'hijopersonal', '' . "\0" . 'AppBundle\\Entity\\Infoadicional' . "\0" . 'alumnoinstituto', '' . "\0" . 'AppBundle\\Entity\\Infoadicional' . "\0" . 'infoadicionalid'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Infoadicional' . "\0" . 'estadosalud', '' . "\0" . 'AppBundle\\Entity\\Infoadicional' . "\0" . 'aspectosinportantes', '' . "\0" . 'AppBundle\\Entity\\Infoadicional' . "\0" . 'necesidadespecial', '' . "\0" . 'AppBundle\\Entity\\Infoadicional' . "\0" . 'descripcionnecesidad', '' . "\0" . 'AppBundle\\Entity\\Infoadicional' . "\0" . 'hijopersonal', '' . "\0" . 'AppBundle\\Entity\\Infoadicional' . "\0" . 'alumnoinstituto', '' . "\0" . 'AppBundle\\Entity\\Infoadicional' . "\0" . 'infoadicionalid'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Infoadicional $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setEstadosalud($estadosalud)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstadosalud', [$estadosalud]);

        return parent::setEstadosalud($estadosalud);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstadosalud()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstadosalud', []);

        return parent::getEstadosalud();
    }

    /**
     * {@inheritDoc}
     */
    public function setAspectosinportantes($aspectosinportantes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAspectosinportantes', [$aspectosinportantes]);

        return parent::setAspectosinportantes($aspectosinportantes);
    }

    /**
     * {@inheritDoc}
     */
    public function getAspectosinportantes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAspectosinportantes', []);

        return parent::getAspectosinportantes();
    }

    /**
     * {@inheritDoc}
     */
    public function setNecesidadespecial($necesidadespecial)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNecesidadespecial', [$necesidadespecial]);

        return parent::setNecesidadespecial($necesidadespecial);
    }

    /**
     * {@inheritDoc}
     */
    public function getNecesidadespecial()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNecesidadespecial', []);

        return parent::getNecesidadespecial();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcionnecesidad($descripcionnecesidad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcionnecesidad', [$descripcionnecesidad]);

        return parent::setDescripcionnecesidad($descripcionnecesidad);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcionnecesidad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcionnecesidad', []);

        return parent::getDescripcionnecesidad();
    }

    /**
     * {@inheritDoc}
     */
    public function setHijopersonal($hijopersonal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHijopersonal', [$hijopersonal]);

        return parent::setHijopersonal($hijopersonal);
    }

    /**
     * {@inheritDoc}
     */
    public function getHijopersonal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHijopersonal', []);

        return parent::getHijopersonal();
    }

    /**
     * {@inheritDoc}
     */
    public function setAlumnoinstituto($alumnoinstituto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAlumnoinstituto', [$alumnoinstituto]);

        return parent::setAlumnoinstituto($alumnoinstituto);
    }

    /**
     * {@inheritDoc}
     */
    public function getAlumnoinstituto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAlumnoinstituto', []);

        return parent::getAlumnoinstituto();
    }

    /**
     * {@inheritDoc}
     */
    public function getInfoadicionalid()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getInfoadicionalid();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInfoadicionalid', []);

        return parent::getInfoadicionalid();
    }

}
