<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class TpRuta extends \AppBundle\Entity\TpRuta implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\TpRuta' . "\0" . 'nombre', '' . "\0" . 'AppBundle\\Entity\\TpRuta' . "\0" . 'capacidad', '' . "\0" . 'AppBundle\\Entity\\TpRuta' . "\0" . 'preciocontrato', '' . "\0" . 'AppBundle\\Entity\\TpRuta' . "\0" . 'tipoviaje', '' . "\0" . 'AppBundle\\Entity\\TpRuta' . "\0" . 'tipoprecio', '' . "\0" . 'AppBundle\\Entity\\TpRuta' . "\0" . 'vigenciainicio', '' . "\0" . 'AppBundle\\Entity\\TpRuta' . "\0" . 'vigenciafin', '' . "\0" . 'AppBundle\\Entity\\TpRuta' . "\0" . 'horainicio', '' . "\0" . 'AppBundle\\Entity\\TpRuta' . "\0" . 'horafin', '' . "\0" . 'AppBundle\\Entity\\TpRuta' . "\0" . 'sabado', '' . "\0" . 'AppBundle\\Entity\\TpRuta' . "\0" . 'domingo', '' . "\0" . 'AppBundle\\Entity\\TpRuta' . "\0" . 'activo', '' . "\0" . 'AppBundle\\Entity\\TpRuta' . "\0" . 'alias', '' . "\0" . 'AppBundle\\Entity\\TpRuta' . "\0" . 'rutaid', '' . "\0" . 'AppBundle\\Entity\\TpRuta' . "\0" . 'subconceptoid'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\TpRuta' . "\0" . 'nombre', '' . "\0" . 'AppBundle\\Entity\\TpRuta' . "\0" . 'capacidad', '' . "\0" . 'AppBundle\\Entity\\TpRuta' . "\0" . 'preciocontrato', '' . "\0" . 'AppBundle\\Entity\\TpRuta' . "\0" . 'tipoviaje', '' . "\0" . 'AppBundle\\Entity\\TpRuta' . "\0" . 'tipoprecio', '' . "\0" . 'AppBundle\\Entity\\TpRuta' . "\0" . 'vigenciainicio', '' . "\0" . 'AppBundle\\Entity\\TpRuta' . "\0" . 'vigenciafin', '' . "\0" . 'AppBundle\\Entity\\TpRuta' . "\0" . 'horainicio', '' . "\0" . 'AppBundle\\Entity\\TpRuta' . "\0" . 'horafin', '' . "\0" . 'AppBundle\\Entity\\TpRuta' . "\0" . 'sabado', '' . "\0" . 'AppBundle\\Entity\\TpRuta' . "\0" . 'domingo', '' . "\0" . 'AppBundle\\Entity\\TpRuta' . "\0" . 'activo', '' . "\0" . 'AppBundle\\Entity\\TpRuta' . "\0" . 'alias', '' . "\0" . 'AppBundle\\Entity\\TpRuta' . "\0" . 'rutaid', '' . "\0" . 'AppBundle\\Entity\\TpRuta' . "\0" . 'subconceptoid'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (TpRuta $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', [$nombre]);

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', []);

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setCapacidad($capacidad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCapacidad', [$capacidad]);

        return parent::setCapacidad($capacidad);
    }

    /**
     * {@inheritDoc}
     */
    public function getCapacidad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCapacidad', []);

        return parent::getCapacidad();
    }

    /**
     * {@inheritDoc}
     */
    public function setPreciocontrato($preciocontrato)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPreciocontrato', [$preciocontrato]);

        return parent::setPreciocontrato($preciocontrato);
    }

    /**
     * {@inheritDoc}
     */
    public function getPreciocontrato()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPreciocontrato', []);

        return parent::getPreciocontrato();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoviaje($tipoviaje)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoviaje', [$tipoviaje]);

        return parent::setTipoviaje($tipoviaje);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoviaje()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoviaje', []);

        return parent::getTipoviaje();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoprecio($tipoprecio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoprecio', [$tipoprecio]);

        return parent::setTipoprecio($tipoprecio);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoprecio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoprecio', []);

        return parent::getTipoprecio();
    }

    /**
     * {@inheritDoc}
     */
    public function setVigenciainicio($vigenciainicio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVigenciainicio', [$vigenciainicio]);

        return parent::setVigenciainicio($vigenciainicio);
    }

    /**
     * {@inheritDoc}
     */
    public function getVigenciainicio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVigenciainicio', []);

        return parent::getVigenciainicio();
    }

    /**
     * {@inheritDoc}
     */
    public function setVigenciafin($vigenciafin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVigenciafin', [$vigenciafin]);

        return parent::setVigenciafin($vigenciafin);
    }

    /**
     * {@inheritDoc}
     */
    public function getVigenciafin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVigenciafin', []);

        return parent::getVigenciafin();
    }

    /**
     * {@inheritDoc}
     */
    public function setHorainicio($horainicio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHorainicio', [$horainicio]);

        return parent::setHorainicio($horainicio);
    }

    /**
     * {@inheritDoc}
     */
    public function getHorainicio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHorainicio', []);

        return parent::getHorainicio();
    }

    /**
     * {@inheritDoc}
     */
    public function setHorafin($horafin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHorafin', [$horafin]);

        return parent::setHorafin($horafin);
    }

    /**
     * {@inheritDoc}
     */
    public function getHorafin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHorafin', []);

        return parent::getHorafin();
    }

    /**
     * {@inheritDoc}
     */
    public function setSabado($sabado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSabado', [$sabado]);

        return parent::setSabado($sabado);
    }

    /**
     * {@inheritDoc}
     */
    public function getSabado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSabado', []);

        return parent::getSabado();
    }

    /**
     * {@inheritDoc}
     */
    public function setDomingo($domingo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDomingo', [$domingo]);

        return parent::setDomingo($domingo);
    }

    /**
     * {@inheritDoc}
     */
    public function getDomingo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDomingo', []);

        return parent::getDomingo();
    }

    /**
     * {@inheritDoc}
     */
    public function setActivo($activo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActivo', [$activo]);

        return parent::setActivo($activo);
    }

    /**
     * {@inheritDoc}
     */
    public function getActivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActivo', []);

        return parent::getActivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setAlias($alias)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAlias', [$alias]);

        return parent::setAlias($alias);
    }

    /**
     * {@inheritDoc}
     */
    public function getAlias()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAlias', []);

        return parent::getAlias();
    }

    /**
     * {@inheritDoc}
     */
    public function getRutaid()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getRutaid();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRutaid', []);

        return parent::getRutaid();
    }

    /**
     * {@inheritDoc}
     */
    public function setSubconceptoid(\AppBundle\Entity\CjSubconcepto $subconceptoid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSubconceptoid', [$subconceptoid]);

        return parent::setSubconceptoid($subconceptoid);
    }

    /**
     * {@inheritDoc}
     */
    public function getSubconceptoid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubconceptoid', []);

        return parent::getSubconceptoid();
    }

}
