<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CeConfiguracionsubmaterias extends \AppBundle\Entity\CeConfiguracionsubmaterias implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\CeConfiguracionsubmaterias' . "\0" . 'porcentajecalificacion', '' . "\0" . 'AppBundle\\Entity\\CeConfiguracionsubmaterias' . "\0" . 'configuracionsubmateriasid', '' . "\0" . 'AppBundle\\Entity\\CeConfiguracionsubmaterias' . "\0" . 'formaconfiguracionsubmateriaid', '' . "\0" . 'AppBundle\\Entity\\CeConfiguracionsubmaterias' . "\0" . 'materiaid'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\CeConfiguracionsubmaterias' . "\0" . 'porcentajecalificacion', '' . "\0" . 'AppBundle\\Entity\\CeConfiguracionsubmaterias' . "\0" . 'configuracionsubmateriasid', '' . "\0" . 'AppBundle\\Entity\\CeConfiguracionsubmaterias' . "\0" . 'formaconfiguracionsubmateriaid', '' . "\0" . 'AppBundle\\Entity\\CeConfiguracionsubmaterias' . "\0" . 'materiaid'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (CeConfiguracionsubmaterias $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setPorcentajecalificacion($porcentajecalificacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPorcentajecalificacion', [$porcentajecalificacion]);

        return parent::setPorcentajecalificacion($porcentajecalificacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getPorcentajecalificacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPorcentajecalificacion', []);

        return parent::getPorcentajecalificacion();
    }

    /**
     * {@inheritDoc}
     */
    public function getConfiguracionsubmateriasid()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getConfiguracionsubmateriasid();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConfiguracionsubmateriasid', []);

        return parent::getConfiguracionsubmateriasid();
    }

    /**
     * {@inheritDoc}
     */
    public function setFormaconfiguracionsubmateriaid(\AppBundle\Entity\CeFormaconfiguracionsubmateria $formaconfiguracionsubmateriaid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFormaconfiguracionsubmateriaid', [$formaconfiguracionsubmateriaid]);

        return parent::setFormaconfiguracionsubmateriaid($formaconfiguracionsubmateriaid);
    }

    /**
     * {@inheritDoc}
     */
    public function getFormaconfiguracionsubmateriaid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFormaconfiguracionsubmateriaid', []);

        return parent::getFormaconfiguracionsubmateriaid();
    }

    /**
     * {@inheritDoc}
     */
    public function setMateriaid(\AppBundle\Entity\Materia $materiaid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMateriaid', [$materiaid]);

        return parent::setMateriaid($materiaid);
    }

    /**
     * {@inheritDoc}
     */
    public function getMateriaid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMateriaid', []);

        return parent::getMateriaid();
    }

}
